### ISSUE TITLE
SyntaxError: invalid syntax in circular-linear-split.py

### ISSUE THREAD

**Issue by miczuppi** [jiarong/VirSorter2#104]
Hi,
I am trying to run virsorter2 on a file but it is giving me this error:
```

File "/mnt/projects/miniconda2/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/circular-linear-split.py", line 63
    mes = (f'Duplicate seqname detected in {infile}; '
                                                     ^
SyntaxError: invalid syntax
```
Could you help me sort this out?

Thank you for your time,
Michele

**Comment by jiarong** [comment]
There is probably some issue with your system PATH setup that leads to python3 installed by VS2 is not used. It's using python2 somehow. To avoid the issue, I recommend the singularity image:
https://github.com/jiarong/VirSorter2#option-3
