### ISSUE TITLE
[Feature] pyhmmer

### ISSUE THREAD

**Issue by alienzj** [jiarong/VirSorter2#109]
Dear @jiarong,
do you have any plan to use pyhmmer instead of hmmer ?
Based on the pyhmmer documentations, when we increase the number of CPU, the speed of hmmsearch will more fast.

![image](https://user-images.githubusercontent.com/8847420/175221620-b72950ab-76e6-469b-b69d-e16161f67a95.png)

**Comment by jiarong** [comment]
Thanks for the suggest. I will take a look, but this is low priority. As mentioned in #53, better parallelism can be achieved by simply splitting the input contig file.
