### ISSUE TITLE
Duplicate seqname

### ISSUE THREAD

**Issue by xiaozhazha123** [jiarong/VirSorter2#112]
Hello,

I tried to run Virsorter2 but I got the following error message:
Duplicate seqname detected in /data/zyu/data/IRD/Asfarviridae.fna; Please make sure all sequence names are unique..
But I didn't find any duplicate sequences.

**Comment by jiarong** [comment]
Hi, the error message indicates you have duplicate sequence name/ID (NOT sequence).
