### ISSUE TITLE
combine genomes

### ISSUE THREAD

**Issue by Biofarmer** [jiarong/VirSorter2#113]
Hi Jiarong,

I am using virsorter2 v2.2.3 for thousands of genomes to check virus sequences. I have a few questions before running:
1. Can I combine all genomes into one file, of course, make sure the names of contigs are unique in the combined file?
2. Run each genome individually or combined file, which way is fast and better based on your experience?

Thanks
Wang

**Comment by Biofarmer** [comment]
OK, thanks. If running genome individually, should I just use 4 threads (-j 4) for each genome as the HMMSEARCH_THREADS is set to 4? With more threads, there is no effect on this hmm search step, right?

**Comment by Biofarmer** [comment]
@jiarong another question, I have installed virsorter2, and databases and dependencies by virsorter setup -d db -j 4 in a computer cluster. The computer cluster is managing with Slurm system, and when the job is submitted, there will be no internet available. May I ask whether any internet is needed when running the job when the databases and dependencies have been installed?

Another question about manually install databases and dependencies, I found that the dependencies in conda_envs is not installed but will be installed when running the first sample, which does not like virsorter setup -d db -j 4 that install dependencies in conda_envs along with downloading databases. May I ask if manually installing databases, whether the dependencies in conda_envs will be installed every time for each samples? or once installed, all rest samples will skip this step?

Thanks

**Comment by jiarong** [comment]
- Right, `-j 4` should be enough for a bacterial genome, and increasing threads wont have much improvement on speed.
1&2: Once db and dependencies are installed, internet connection is NOT needed, and dependency installation is skipped.
3. This could happen. HMMER can be limited by things other than CPU. In computer clusters, it's likely the speed to read the data over network. It usually takes 10 - 20 mins on my server.

**Comment by jiarong** [comment]
Dependencies can only be installed automatically. Usually, running the test example should have that done.

**Comment by Biofarmer** [comment]
> Dependencies can only be installed automatically. Usually, running the test example should have that done.

Yes, I run the test and found that dependencies have been installed automatically. But after running 'virsorter config --init-source --db-dir=./db' and before running test example, conda_envs in /db directory is empty and dependencies are not installed, right?

**Comment by jiarong** [comment]
Correct.

**Comment by Biofarmer** [comment]
Thanks and it is good to know more about the virsorter2. May I a bit confirm whether the manually downloaded database (https://osf.io/v46sc/download) is updated and completely same as the database by 'virsorter setup' command (virsorter setup -d db -j 4)?
Thanks

**Comment by Biofarmer** [comment]
@jiarong sorry, a following question, the virus sequence is identified only within each contig, not cross contigs, right?
Thanks

**Comment by jiarong** [comment]
- right, the database manually downloaded is the same as the one installed by `virsorter setup`.

1. correct, NOT across contigs.
2. If you follow the SOP, the ends trimming is done by checkV.
3. Classification of viral sequences is not covered by the SOP, but it typically needs >5kb to have reliable taxonomy assignment.

**Comment by Biofarmer** [comment]
@jiarong Thank you very much!
