### ISSUE TITLE
virsorter2(2.2.3) stay starked and in quiet without any errors after listing all snakemake jobs

### ISSUE THREAD

**Issue by liupfskygre** [jiarong/VirSorter2#119]
Hi，Jiarong
    I am running virsorter2, with several samples successfully done on server. However, when i try to run new samples, it just list all snakemake jobs and stay quiet without running, just in quiet and without giving any error messages. 

#following is the screen info:
```
 Executing: snakemake --snakefile /home/huangxingyu/anaconda3/envs/vs2/lib/
python3.8/site-packages/virsorter/Snakefile --directory /mnt/local_48t/huangxingyu/workflow/Projec
ts_liupf/glacier_contigs_partI_1k.out --jobs 40 --configfile /mnt/local_48t/huangxingyu/workflow/P
rojects_liupf/glacier_contigs_partI_1k.out/config.yaml --latency-wait 600 --rerun-incomplete --nol
ock --conda-frontend mamba --conda-prefix /mnt/local_48t/huangxingyu/database/virsorterdb/conda_e
nvs --use-conda --quiet all 

job counts:
..... (omit the whole list)

5 split_gff_by_group
121
```

it stays here in quiet without any error message or running

Any suggestions to overcome this and make virsorter2 running again?

Thanks. 

Pengfei

**Comment by XingChengguang** [comment]
I meet the same problem

**Comment by jiarong** [comment]
The first annotation step is slow, and can take a long time for large sample without any output to the screen. Since the same script works for some samples, it should work for other samples.

**Comment by liupfskygre** [comment]
Thanks.  I use top to check the jobs running on our server and also seems nothing is running, with zero RAM and core usage. is this normal for the first annotation step to prepare？

**Comment by liupfskygre** [comment]
Hi, jiarong,
      I try to use a very small dataset for testing, but still stay in quiet without any errors and not running. 
not sure what is going on.
any suggestions?

thanks.

**Comment by jiarong** [comment]
What's the messages printed to the screen before it stay quiet for the smaller dataset?

**Comment by liupfskygre** [comment]
nothing happened, just list all jobs and stay quiet as listed above.

**Comment by jiarong** [comment]
That means it did not start the first step (preprocess). Not sure what's cause. Can you send me the small dataset? guojiaro near gmail.com

**Comment by liupfskygre** [comment]
Hi, we tried several small datasets,  including the testing on here，https://raw.githubusercontent.com/jiarong/VirSorter2/master/test/8seq.fa, but still the same

**Comment by jiarong** [comment]
I ran with test data and it is working on my end. Maybe there is some issue with your conda setting. You can try installation [option 3](https://github.com/jiarong/VirSorter2#option-3) to see it works.

**Comment by liupfskygre** [comment]
Hi, jiarong, 
    we test on another server and it worked. we guess it might be caused by the io of our server. now we try to fix it with our Adm.

thanks
