### ISSUE TITLE
Snakemake requirement hard-set to 5.16

### ISSUE THREAD

**Issue by apcamargo** [jiarong/VirSorter2#12]
Hey!

I noticed that VirSorter2 requires Snakemake 5.16. I've been using more recent versions of Snakemake due to improvements for using it with Google Cloud. Is there any reason for VirSorter requiring version 5.16? I executed it with a more recent version and had no obvious errors.

Thanks!

**Comment by jiarong** [comment]
I specified the a snakemake version due to some bug with conda not installing the most updated version if I only set a minimal version. 5.16 was the most updated when I started. Feel free to use most updated snakemake.

**Comment by apcamargo** [comment]
That's strange. I always create my environments like this (setting a minimal version).

Anyway, thank you for your answer!
