### ISSUE TITLE
Question about virsorter SOP and using checkV

### ISSUE THREAD

**Issue by yugen-miyahara** [jiarong/VirSorter2#125]
Hi there,

Virsorter is great! I had a question about the SOP. The SOP is for putting inputs into DRAM and you use checkV to get rid of non-viral sequences and trim proviruses. But that is for AMG identification. For virus classification with vContact2 I can't find anywhere that puts virsorter output first into checkV before running vContact2. Is this something that should be done?

Many thanks,
Yugen

**Comment by yugen-miyahara** [comment]
Quality control
The default score cutoff (0.5) works well known viruses (RefSeq). For the real environmental data, we can expect to get false positives (non-viral) with the default cutoff. Generally, samples with more host (e.g. bulk metaG) and unknown sequences (e.g. soil) tends to have more false positives. We find a score cutoff of 0.9 work well as a cutoff for high confidence hits, but there are also many viral hits with score <0.9. It's difficult to separate the viral and non-viral hits by score alone. So we recommend using the default score cutoff (0.5) for maximal sensitivity and then applying a quality checking step using checkV. Here is a tutorial of [viral identification SOP](https://www.protocols.io/view/viral-sequence-identification-sop-with-virsorter2-btv8nn9w) used in Sullivan Lab.

**Comment by jiarong** [comment]
After you run SOP, you can use the viral contigs as input to vContact2.
