### ISSUE TITLE
How can one speed up the run? (particularly hmmsearch)

### ISSUE THREAD

**Issue by fluhus** [jiarong/VirSorter2#127]
Hello,

I installed VS2 as explained in the README in option 1 and I am now running `virsorter run -w test.out -i my_contigs.fa -j 4 all`.

The size of the fasta file is 1.3MB and it takes 20-25 minutes to finish. I would like to see how I can speed this up since I have about 50,000 files to analyze (I hope that's reasonable!). Running `top` I saw that 99% of the time is spent on `hmmsearch`.

So far I have tried running `config --set HMMSEARCH_THREADS=4` which printed `HMMSEARCH_THREADS: 2 ==> 4`, but I am still seeing the process using only 100% CPU. I also tried running with `--provirus-off` and `--max-orf-per-seq 10` or `20` which didn't help. Running with `--min-length` didn't change because the contigs were filtered for length in advance.

Any advice on what can help with the computation speed?
I am new to VS2 and hmmsearch so any insight is welcome :). I am ok with losing some accuracy if needed.

Thanks

**Comment by jiarong** [comment]
Hi,  hmmsearch is not very parallelizable, and its speed is limited by IO mostly. Thus increasing threads to >2 has little improvement at speed. 
One strategy is to split the input and run more hmmsearch as separate process. You can do this on your own. In VS2, `config --set FAA_BP_PER_SPLIT=50000` ( the default is 10000000) can facilitate this. Of course, this strategy assume you have enough CPUs.
To reduce the total CPUtime, reducing `--max-orf-per-seq` is the only solution.

**Comment by fluhus** [comment]
Thanks! I'll try what you said.
