### ISSUE TITLE
error when running test.fa

### ISSUE THREAD

**Issue by TJrogers86** [jiarong/VirSorter2#128]
Hello,

I am receiving a similar error to others after installing VS2, but there doesnt seem to be a fix. I have installed both the developmental version and the conda version only to get the same error. I then tried to install the singularity build version, but the terminal screen turns into a bunch of blue X's and S's (see photos below):

Error when using conda and developmental versions:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/48442658/188233867-e6dcf468-3201-4009-9ad3-87373289fe7d.png">

Strange behavior when installing the singularity build version:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/48442658/188234076-2cc543eb-8871-45bf-8469-75a89de05e8f.png">

**Comment by jiarong** [comment]
Hi, some of your PATH setting is making `conda` env not working. Just renaming `/home/lloydlab/.local` to something else might work, but other things installed there might stop working.
Singularity has been renamed to apptainer and is the best solution. You can follow the link below to install. It's a little technical. I would suggest asking your server sys admin to do that.
https://apptainer.org/docs/admin/main/installation.html#installation-on-linux

**Comment by matheuscrgarcia** [comment]
I had the same problem, what is happening is that your CONDA is using the sklearn installed in your computer(which is probably not the required version of virsorter2), not the one installed in the env. So, to fix this jus uninstall the sklearn version of your system. I also found out that you can isolate your conda env from your computer(and therefore the conda will be unable to reach any preinstalled package) by using this command: export PYTHONNOUSERSITE=True; but I havent used this, I just deleted the system wide version.

**Comment by TJrogers86** [comment]
Thanks both of you. Ill give these suggestions a try and see if it fixes the issues
