### ISSUE TITLE
Can Virsorter2 detect new virus?

### ISSUE THREAD

**Issue by woodoo46** [jiarong/VirSorter2#131]
Hi there,

I am wondering if VirSorter2 is suitable for detecting new virus?

Thanks.

George

**Comment by jiarong** [comment]
Yes. It's easy case to identify if the new virus has a few hallmark genes such as capsid protein for dsDNA virus. VirSorter2 also has some features not related to existing viral ref sequences, such as lower strand switch frequency and small gene size that are more effective for new virus.
