### ISSUE TITLE
Issues with prep for DRAM

### ISSUE THREAD

**Issue by del-oxyribonucleic-acid** [jiarong/VirSorter2#137]
Hello! I have been trying to convert my virsorter2 results to be able to import them into anvio, and need to use the prep-for-dram vflag but have been getting some odd errors.

I tried running vs2 again with the flag --prep-for-dramv, but it seems to be running the whole vs2 pipeline again? I tried using the classify mode to make it skip the first two steps but that didn't seem to work either. When I attempt to run it on the whole directory, it says it can't find the yaml file even though it's there in the directory. I also checked and made sure the yaml file looks good and isn't empty and it looks fine to me. I was directed here from the VirSorter2_to_Anvio (https://github.com/simroux/VirSorter2_to_Anvio) GitHub page. Any help is greatly appreciated, thanks!

`(vs2) delaney@ada:~/5YV/JGI_assemblies/SH_QC_derep/31_VS2_results_by_sample/2013_11_13_Gb0149061_derep.fasta.output$ ls
2013_11_13_Gb0149061_final-viral-boundary.tsv  2013_11_13_Gb0149061_final-viral-score.tsv  final-viral-boundary.tsv  final-viral-score.tsv  log   test-dramv
2013_11_13_Gb0149061_final-viral-combined.fa   config.yaml                                 final-viral-combined.fa   iter-0                 test
(vs2) delaney@ada:~/5YV/JGI_assemblies/SH_QC_derep/31_VS2_results_by_sample/2013_11_13_Gb0149061_derep.fasta.output$ virsorter run -w test-dramv -i 2013_11_13_Gb0149061_final-viral-combined.fa --prep-for-dramv classify
[2022-10-12 11:06 INFO] VirSorter 2.2.3
[2022-10-12 11:06 INFO] /home/delaney/miniconda3/envs/vs2/bin/virsorter run -w test-dramv -i 2013_11_13_Gb0149061_final-viral-combined.fa --prep-for-dramv classify
[2022-10-12 11:06 CRITICAL] No config.yaml dectected from previous run`

**Comment by jiarong** [comment]
Hi, to the skip the first two steps, the command should be the same as the first time you run it except for adding `--prep-for-dramv classify` at the end. From the info provided, my best guess of the command is:
 ```
virsorter run -w ~/5YV/JGI_assemblies/SH_QC_derep/31_VS2_results_by_sample/2013_11_13_Gb0149061_derep.fasta.output  -i ~/5YV/JGI_assemblies/SH_QC_derep/31_VS2_results_by_sample/2013_11_13_Gb0149061_derep.fasta --prep-for-dramv classify
```

**Comment by del-oxyribonucleic-acid** [comment]
Hi -
Thanks for your quick response! That is how I wrote the command I believe (copied from above):
`delaney@ada:~/5YV/JGI_assemblies/SH_QC_derep/31_VS2_results_by_sample/2013_11_13_Gb0149061_derep.fasta.output$ virsorter run -w test-dramv -i 2013_11_13_Gb0149061_final-viral-combined.fa --prep-for-dramv classify`

**Comment by jiarong** [comment]
Hi, that's the command w/ `--prep-for-dramv`. What's the command when you ran w/o `--prep-for-dramv`?

**Comment by del-oxyribonucleic-acid** [comment]
Oh sorry! I ran it using this script: 

`#!/bin/bash -i

DECON_FOLDER="/home/delaney/5YV/JGI_assemblies/SH_QC_derep/04_read_mapping_per_sample/reads_per_sample_NAMES"
ASSEMBLY_RESULTS="/home/delaney/5YV/JGI_assemblies/SH_QC_derep/04_read_mapping_per_sample/assemblies_per_sample_NAMES"
#spades_RESULTS=$ASSEMBLY_RESULTS/metaspades3
FINAL_ASSEMBLY="/home/delaney/5YV/JGI_assemblies/SH_QC_derep/SPOT5Yr.fa"

BY_SAMPLE_RESULTS="31_VS2_results_by_sample"
mkdir -p $BY_SAMPLE_RESULTS


conda activate vs2

for f in `ls ${ASSEMBLY_RESULTS}/*_derep.fasta`; do
	org_name=${f}
        BASENAME=$(basename $org_name)
        FILESTEM="${BASENAME%_derep.fasta}"

	virsorter run -w ${BY_SAMPLE_RESULTS}/${BASENAME}.output -i ${org_name} -j 15 --min-score 0.9

	echo "${org_name} done"


done


conda deactivate
`

**Comment by jiarong** [comment]
You just need to append `--prep-for-dramv classify`  to the `virsorter run` line and resubmit the script.
