### ISSUE TITLE
Error in rule merge_split_faa_gff

### ISSUE THREAD

**Issue by erichy91** [jiarong/VirSorter2#138]
Hello,

I have an error at the merge_split_faa_gff step, and this is the error message: 

```
Error in rule merge_split_faa_gff:
    jobid: 64
    output: iter-0/pp-linear.gff, iter-0/pp-linear.faa
    conda-env: /mnt/DATA1/etienne/program/VirSorter2/db/conda_envs/db5b2919
    shell:
        
        printf "%s
" iter-0/pp-linear.fna.splitdir/pp-linear.fna.389.split.pdg.splitgff iter-0/pp-linear.fna.splitdir/pp-linear.fna.841.split.pdg.splitgff iter-0/pp-linear.fna.splitdir/pp-linear.fna.301.split.pdg.splitgff iter-0/pp-linear.fna.splitdir/pp-linear.fna.11

.....

iter-0/pp-linear.fna.splitdir/pp-linear.fna.381.split iter-0/pp-linear.fna.splitdir/pp-linear.fna.831.split iter-0/pp-linear.fna.splitdir/pp-linear.fna.24.split iter-0/pp-linear.fna.splitdir/pp-linear.fna.504.split iter-0/pp-linear.fna.splitdir/pp-linear.fna.739.split | xargs rm -f
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

```

Do you have any idea what is going on? I tried running the test and it works fine, I also tried reinstalling virsorter2, removing the line breaks in my fasta file like in the test file but I get the same error.

Any help is greatly appreciated, 
Thanks in advance!

**Comment by jiarong** [comment]
Hi, 
1) what's your OS? you can check by `cat /etc/os-release`.
2) VirSorter2 generate many intermediate files, so make sure you are within the max file # limit. Try `virsorter config --set MAX_SPLIT=100`, rerun, and see if it helps.

**Comment by erichy91** [comment]
Hi,

My OS version is 8.2
I just changed the maximum file limit, and I got the same result.

**Comment by erichy91** [comment]
Is it possible that the size of the fasta file could crash virsorter? Splitting the fasta or increasing the --min-length threshold worked for me. 
Thanks for your help.

**Comment by jiarong** [comment]
The size of fasta should not crash. VS2 does the splitting internally too. The only reason I can think of is you are approaching your disk space limit or max # of files allowed.
