### ISSUE TITLE
Prophage detection and coordinates

### ISSUE THREAD

**Issue by asierFernandezP** [jiarong/VirSorter2#139]
In the VirSorter2 paper you compare its performance on provirus detection on a selection of bacterial genomes with known proviruses, and identify as true positives those proviruses for which  ≥50% of their genome was recovered.

Moreover, in the GitHub you describe that partial sequences can be treated as proviruses since they are extracted from longer host sequences, but full sequences, however, can be proviruses or free virus.

So, it is possible to get from VirSorter2 a list of all identified proviruses (and their coordinates)? Or we should only consider as proviruses those classified as "partial", ignoring those classified as "full". Is there a way to curate/check them?

Thank you

**Comment by jiarong** [comment]
Good Q. In VirSorter2 results, those with "partial" suffix (meaning the contig is only partially viral) are good high confidence prophage. You can find the ends of prophage in the `final-viral-boundary.tsv`. The ends are proximate and needs further curation.  Those with "full" suffix could be prophage too, eg. viral sequence w/ one or two unknown/non-typical viral gene at the ends that hard to tell if they are part of the virus. For curation, you need to look the annotation (eg. DRAMv) of genes near boundary and judge on your own. Here curation tips related to prophage in the VirSorter2 SOP might be of interest: 
https://www.protocols.io/view/viral-sequence-identification-sop-with-virsorter2-5qpvoyqebg4o/v3?version_warning=no&step=5
You can also use other prophage tools to maximize the prophage hits.
Hope it helps.

**Comment by asierFernandezP** [comment]
Thank you for the answer!
