### ISSUE TITLE
Best assembly for further usage in VirSorter2

### ISSUE THREAD

**Issue by deminatanja** [jiarong/VirSorter2#140]
Hi,
Do I understand right that the input file may be from any assembler?
Do you have any data/observation, which assembly tool gives the best metagenomic assemblies in terms of further screening for viral sequences by VirSorter2?
BR,
Tatiana

**Comment by jiarong** [comment]
Hi,
Correct, input is contigs in fasta format, which can be from any assembler. It's a choice of assembly tool that give you better assembly (longer contigs).  In general, spades works pretty work. With larger dataset, megahit works better. Hope this helps.

**Comment by deminatanja** [comment]
Thank you!
