### ISSUE TITLE
Headers in final-viral-combined.fa

### ISSUE THREAD

**Issue by deminatanja** [jiarong/VirSorter2#141]
Hi,

Is the output file final-viral-combined.fa supposed to have the headers in the format >Caudo-circular||full    shape:circular||start:327||end:32076||group:dsDNAphage||score:0.993||hallmark:4? I got it as  >Caudo-circular||full only. What could be the reason?

BR,
Tatiana

**Comment by jiarong** [comment]
Hi, that's expected in `final-viral-combined.fa`. You can find other info in  `final-viral-score.tsv` or `final-viral-boundary.tsv`.
