### ISSUE TITLE
cat: iter-0/pp-circular.fna.splitdir/pp-circular.fna.0.split.pdg.splitgff: No such file or directory

### ISSUE THREAD

**Issue by cho7-31** [jiarong/VirSorter2#144]
Hi, 
I try for the first time virsorter and I've got an error that I don't understand.
I'm running VirSorter 2.2.3 with contigs from metagenome as input.

[2022-12-10 15:46 INFO] # of seqs < 5000 bp and removed: 527068
[2022-12-10 15:46 INFO] # of circular seqs: 24
[2022-12-10 15:46 INFO] # of linear seqs  : 16145
[2022-12-10 15:46 INFO] Finish spliting circular contig file with common rbs
[2022-12-10 15:46 INFO] Finish spliting linear contig file with common rbs
cat: iter-0/pp-circular.fna.splitdir/pp-circular.fna.0.split.pdg.splitgff: No such file or directory
[Sat Dec 10 15:47:00 2022]
Error in rule merge_split_faa_gff:
    jobid: 88
    output: iter-0/pp-circular.gff, iter-0/pp-circular.faa
    conda-env: /usr/local/bioinfo/src/VirSorter2/VirSorter2-v2.2.3/db/conda_envs/0db5564d
    shell:

        printf "%s
" iter-0/pp-circular.fna.splitdir/pp-circular.fna.0.split.pdg.splitgff | xargs cat > iter-0/pp-circular.gff
        printf "%s
" iter-0/pp-circular.fna.splitdir/pp-circular.fna.0.split.pdg.splitfaa | xargs cat > iter-0/pp-circular.faa
        printf "%s
" iter-0/pp-circular.fna.splitdir/pp-circular.fna.0.split | xargs rm -f

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues

In the log file circular-remove-partial-gene-common.log
I've the following error : FileNotFoundError: [Errno 2] No such file or directory: 'iter-0/pp-circular.gff'

Do you have any idea to help me ?

Thanks a lot !

**Comment by jiarong** [comment]
Hi, I have not seen this error before. Since VirSorter2 is complaining a file that is supposed to be there is actually not there, it's likely there is some hardware issue w/ computer or server you are running, especially disk issues. Did you run successfully with test example?

**Comment by cho7-31** [comment]
Thanks it's ok now. In fact I've made a local error because I used the same directory for several samples. So it erased files. It was my fault. Thanks again.
