### ISSUE TITLE
error of "AttributeError: module 'numpy' has no attribute 'float'"

### ISSUE THREAD

**Issue by ChaoLab** [jiarong/VirSorter2#145]
Hi,
I used the following commands to set up the conda env and db:
```
mamba create -c conda-forge -c bioconda -p /slowdata/yml_environments/ViWrap-vs2 python=3.8 virsorter==2.2.3 numpy=1.20.0 -y
conda run -p /slowdata/yml_environments/ViWrap-vs2 virsorter setup -d /storage1/data11/ViWrap/ViWrap_db/VirSorter2_db -j 10
```

After I run with the test.fa, I got an error report as:
```
AttributeError: module 'numpy' has no attribute 'float'
in .../test.out/log/iter-0/step3-classify/all-score-ssDNA.log
```

Do you know where is the problem?
[tmp_test.log](https://github.com/jiarong/VirSorter2/files/10301855/tmp_test.log)

[test.out.zip](https://github.com/jiarong/VirSorter2/files/10301856/test.out.zip)

**Comment by yqy6611** [comment]
That's due to the removal of float attribute in the latest numpy. In database construction phase, latest numpy will be invoked in conda_env in your database folder. Use -s to skip dependency installation when executing virsorter setup.

**Comment by ChaoLab** [comment]
> That's due to the removal of float attribute in the latest numpy. Implement Option 2 and add numpy=1.23 into vs2.yaml. Execute virsorter setup successively.

Can you be more specific? where is the vs2.yaml?

**Comment by jiarong** [comment]
Thanks for reporting the error and solutions.
To be more specific,  `numpy<1.24` needs to be added to `virsorter/envs/vs2.yaml` in installation option 2. The installation option 3 should still work as it is. I will update `bioconda` version ASAP.

**Comment by danielarothschild** [comment]
Hi @jiarong I just had the same error when running it (downloaded using the conda version). Has the conda version been updated? otherwise, how can I solve it manually?

Thanks!

**Comment by jiarong** [comment]
@danielarothschild The conda version has been updated (v2.2.4) . Sorry the delay. I need to solve a few other issues in the new release.
