### ISSUE TITLE
Dear VirSorter2 team

### ISSUE THREAD

**Issue by 778055611** [jiarong/VirSorter2#151]
thanks for your aawesome work that helps me a lot, but when I use virsorter2 to identifacation virsu contig from my metagenome contig,Idont konw how to set the "--min-length"parameter. could you please give me some advice . thank you again.

**Comment by jiarong** [comment]
I recommend using this protocol:
https://www.protocols.io/view/viral-sequence-identification-sop-with-virsorter2-5qpvoyqebg4o/v3
