### ISSUE TITLE
Preprocess

### ISSUE THREAD

**Issue by LeoBusse** [jiarong/VirSorter2#16]
Hi, I was just wondering -  do the preprocess results correspond to the viral number of sequences identified in a file? It makes sense for the circular sequences, but I just wanted to double check if the linear sequence output corresponded to the same thing. Thanks!

**Comment by jiarong** [comment]
Hi, the # printed from preprocess is only for detecting circular or linear sequences, and they have nothing to do with viral or nonviral.
