### ISSUE TITLE
Error in Preprocess step

### ISSUE THREAD

**Issue by marctormo** [jiarong/VirSorter2#17]
Hello!

I'm using Virsorter2 for the first time with several samples, but I'm getting an error with one of them:
[2020-11-19 12:27 INFO] conig file written to /gpfs42/robbyfs/scratch/lab_genomica/mtormo/NextSeq_200921/virsorter2/PF1_S6/config.yaml

[2020-11-19 12:27 INFO] Executing: snakemake --snakefile /gpfs42/robbyfs/homes/users/mtormo/VirSorter2/virsorter/Snakefile --directory /gpfs42/ro
bbyfs/scratch/lab_genomica/mtormo/NextSeq_200921/virsorter2/PF1_S6 --jobs 4 --configfile /gpfs42/robbyfs/scratch/lab_genomica/mtormo/NextSeq_2009
21/virsorter2/PF1_S6/config.yaml --conda-prefix /gpfs42/robbyfs/homes/users/mtormo/VirSorter2/db/conda_envs --rerun-incomplete --use-conda --nolo
ck --latency-wait 600   --quiet  all   
Job counts:
	count	jobs
	1	all
	1	circular_linear_split
	1	classify
	5	classify_by_group
	5	classify_full_and_part_by_group
	1	combine_linear_circular
	5	combine_linear_circular_by_group
	1	extract_feature
	1	extract_provirus_seqs
	1	finalize
	1	gff_feature
	5	gff_feature_by_group
	5	hmm_features_by_group
	1	hmm_sort_to_best_hit_taxon
	5	hmm_sort_to_best_hit_taxon_by_group
	1	merge_classification
	1	merge_full_and_part_classification
	5	merge_hmm_gff_features_by_group
	5	merge_provirus_call_by_group_by_split
	1	merge_provirus_call_from_groups
	5	merge_split_hmmtbl
	25	merge_split_hmmtbl_by_group
	25	merge_split_hmmtbl_by_group_tmp
	1	pick_viral_fullseq
	1	preprocess
	1	split_faa
	5	split_faa_by_group
	5	split_gff_by_group
	120
[2020-11-19 12:27 INFO] # of seqs < 0 bp and removed: 0
[2020-11-19 12:27 INFO] # of circular seqs: 0
[2020-11-19 12:27 INFO] # of linear seqs  : 26
[2020-11-19 12:27 INFO] No circular seqs found in contig file
MissingInputException in line 279 of /gpfs42/robbyfs/homes/users/mtormo/VirSorter2/virsorter/rules/preprocess.smk:
Missing input files for rule combine_linear_circular:
iter-0/pp-circular.fna.preext
Exiting because a job execution failed. Look above for error message
[2020-11-19 12:27 CRITICAL] Command 'snakemake --snakefile /gpfs42/robbyfs/homes/users/mtormo/VirSorter2/virsorter/Snakefile --directory /gpfs42/
robbyfs/scratch/lab_genomica/mtormo/NextSeq_200921/virsorter2/PF1_S6 --jobs 4 --configfile /gpfs42/robbyfs/scratch/lab_genomica/mtormo/NextSeq_20
0921/virsorter2/PF1_S6/config.yaml --conda-prefix /gpfs42/robbyfs/homes/users/mtormo/VirSorter2/db/conda_envs --rerun-incomplete --use-conda --no
lock --latency-wait 600   --quiet  all   ' returned non-zero exit status 1.

I don't know what's the problem here. Is it something about the installation? (I ran several samples without any issues) 

Many thanks!
Marc

**Comment by jiarong** [comment]
Hi Marc, the issue with no circular sequence with the most updated development version. You can follow the instructions on installation in README.

**Comment by marctormo** [comment]
Thank you!

But I installed the development version one week ago, and as I can see, the last version is from 25 days ago.
Is there another recent version that I can't see?

Thanks again,
Marc

**Comment by jiarong** [comment]
I have a few updates and tested the updated version with data having no circular sequences, which finishes successfully. Please update to the new development version and see the problem is solved.

**Comment by marctormo** [comment]
Many thanks, the issue is solved now!
Best,
Marc
