### ISSUE TITLE
long-reads

### ISSUE THREAD

**Issue by lucyintheskyzzz** [jiarong/VirSorter2#175]
Hi,

I was wondering if Virsorter2 can be used for nanopore long-read sequences that aren't de novo assembled? Some of my fastq files can be de novo assembled to create a fasta file, but some are not and are in fastq.gz file.  Can I use VirSorter2 on my fastq.gz unassembled reads? 

Thanks! Katie

**Comment by jiarong** [comment]
Hi, Virsorter2 depends on good gene prediction to assign scores, so it depends on quality of your reads. Raw nanopore reads have high insertion/deletion error that can impact gene prediction. Quality control and read error correction step can help.

**Comment by lucyintheskyzzz** [comment]
Hi @jiarong I use medaka polishing for read error correction. Is there an example of what the output file looks like for predicting viral families?

thanks

**Comment by jiarong** [comment]
Hi, here is the (output format)[https://github.com/jiarong/VirSorter2#detailed-description-on-output-files]. Virsorter2 does not assign viral taxonomy tho. For that, I recommend (vContact2)[https://bitbucket.org/MAVERICLab/vcontact2/src/master/]. Here is tutorial on the whole workflow:
https://maveric-informatics.readthedocs.io/en/latest/Processing-a-Viral-Metagenome.html#identifying-viruses

**Comment by lucyintheskyzzz** [comment]
Hi @jiarong thank you for your information!
