### ISSUE TITLE
Error:Duplicate seqname detected in .../....fna,Please make sure all sequence names are unique..

### ISSUE THREAD

**Issue by eiko33** [jiarong/VirSorter2#184]
Hello,
I tried to run Virsorter2 but I got the following error message:
Duplicate seqname detected in /.fna; Please make sure all sequence names are unique..
I used the seqkit software and the uniq command to remove adjacent duplicate rows, trying to retain only the first occurrence of the gene sequence name, but both software showed no duplicate results for either IDs or sequences, and still could not run the program properly.Thank you for your help!

**Comment by jiarong** [comment]
Hi, the way I usually recommend to deal with duplicate names is just to rename the sequence name/ID.
