### ISSUE TITLE
singluarity

### ISSUE THREAD

**Issue by wuhuiyun07** [jiarong/VirSorter2#185]
cannot find db. Where is the db if I use the singularity image?

"You will get a file virsorter2.sif, which is a singularity image that can be run like a binary executable file. You can use the absolute path of this file to replace virsorter in commands for the rest of the tutorial. Also this image has the database and dependencies included, so you can skip the [Download database and dependencies step](https://github.com/jiarong/VirSorter2#download-database-and-dependencies) below."

**Comment by jiarong** [comment]
Hi, you do not need to specify the DB (`--db-dir`) with singularity image. The default should work.
