### ISSUE TITLE
how does VirSorter2 distinguish circular sequences?

### ISSUE THREAD

**Issue by marade** [jiarong/VirSorter2#186]
I can't seem to find this documented anywhere. Some sequence annotators use "circular=True" or "[topology=circular]" in the header, but that does not appear to be the case here. If I'm reading circular-linear-split.py correctly, the expectation for circular sequences is that the head and tail will overlap to some degree? Is that true? When NCBI publishes, say, circular bacterial chromosomes, they don't overlap in this way, right? So what is the purpose of distinguishing circular sequences if they must overlap?

**Comment by jiarong** [comment]
Hi, I am not sure I get your point on circular bacterial genomes: "When NCBI publishes, say, circular bacterial chromosomes, they don't overlap in this way".  What other ways are there? 
Anyways, your understanding of the `circular-linear-split.py` is correct. The main purpose is to make sure genes in the overlap region are not counted twice that could mess up the downstream prediction.

**Comment by marade** [comment]
The other way, which is widely used, is to have no overlap and only specify it in the header. Thus the circular sequence can be rotated. Thanks for your answer.
