### ISSUE TITLE
run a test: Error in rule circular_linear_split:

### ISSUE THREAD

**Issue by tianyi1616** [jiarong/VirSorter2#194]
~/meta/vs2$     virsorter run -w ~/meta/vs2/test.out -i ~/meta/vs2/8seq.fa  --min-length 1500 -j 4 all
[2024-04-03 03:12 INFO] VirSorter 2.2.4
[2024-04-03 03:12 INFO] /home/tian/mambaforge/envs/vs2/bin/virsorter run -w /home/tian/meta/vs2/test.out -i /home/tian/meta/vs2/8seq.fa --min-length 1500 -j 4 all
[2024-04-03 03:12 INFO] Using /home/tian/mambaforge/envs/vs2/lib/python3.10/site-packages/virsorter/template-config.yaml as config template
[2024-04-03 03:12 INFO] conig file written to /home/tian/meta/vs2/test.out/config.yaml

[2024-04-03 03:12 INFO] Executing: snakemake --snakefile /home/tian/mambaforge/envs/vs2/lib/python3.10/site-packages/virsorter/Snakefile --directory /home/tian/meta/vs2/test.out --jobs 4 --configfile /home/tian/meta/vs2/test.out/config.yaml --latency-wait 600 --rerun-incomplete --nolock  --conda-frontend mamba --conda-prefix /home/tian/meta/vs2/db/conda_envs --use-conda    --quiet  all   
Job counts:
        count   jobs
        1       all
        1       check_point_for_reclassify
        1       circular_linear_split
        1       classify
        2       classify_by_group
        2       classify_full_and_part_by_group
        1       combine_linear_circular
        2       combine_linear_circular_by_group
        1       extract_feature
        1       extract_provirus_seqs
        1       finalize
        1       gff_feature
        2       gff_feature_by_group
        2       hmm_features_by_group
        1       hmm_sort_to_best_hit_taxon
        2       hmm_sort_to_best_hit_taxon_by_group
        1       merge_classification
        1       merge_full_and_part_classification
        2       merge_hmm_gff_features_by_group
        2       merge_provirus_call_by_group_by_split
        1       merge_provirus_call_from_groups
        5       merge_split_hmmtbl
        10      merge_split_hmmtbl_by_group
        10      merge_split_hmmtbl_by_group_tmp
        1       pick_viral_fullseq
        1       preprocess
        1       split_faa
        2       split_faa_by_group
        2       split_gff_by_group
        61
Traceback (most recent call last):
  File "/home/tian/mambaforge/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py", line 98, in <module>
    main()
  File "/home/tian/mambaforge/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py", line 59, in main
    for rec in screed.open(infile):
  File "/home/tian/meta/vs2/db/conda_envs/37979374/lib/python3.8/site-packages/screed/openscreed.py", line 35, in __init__
    self.iter_fn = self.open_reader(filename, *args, **kwargs)
  File "/home/tian/meta/vs2/db/conda_envs/37979374/lib/python3.8/site-packages/screed/openscreed.py", line 94, in open_reader
    raise ValueError("unknown file format for '%s'" % filename)
ValueError: unknown file format for '/home/tian/meta/vs2/8seq.fa'
[Wed Apr  3 03:12:25 2024]
`Error` in rule circular_linear_split:
    jobid: 8
    output: iter-0/pp-seqname-length.tsv
    conda-env: /home/tian/meta/vs2/db/conda_envs/37979374
    shell:
        
        # prep_logdir
        mkdir -p log/iter-0/step1-pp log/iter-0/step2-extract-feature log/iter-0/step3-classify

        Cnt=$(grep -c '^>' /home/tian/meta/vs2/8seq.fa)
        if [ ${Cnt} = 0 ]; then
            echo "No sequnences found in contig file; exiting"               | python /home/tian/mambaforge/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py --level error
            exit 1
        fi 

        python /home/tian/mambaforge/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-linear-split.py           /home/tian/meta/vs2/8seq.fa           iter-0/pp-circular.fna.preext          iter-0/pp-linear.fna           iter-0/pp-seqname-length.tsv           "||rbs:common"           1500

        if [ ! -s iter-0/pp-circular.fna.preext ]; then
            echo "No circular seqs found in contig file"               | python /home/tian/mambaforge/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-circular.fna.preext
        else
            python /home/tian/mambaforge/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/circular-extend.py               iter-0/pp-circular.fna.preext iter-0/pp-circular.fna
        fi

        if [ ! -s iter-0/pp-linear.fna ]; then
            echo "No linear seqs found in contig file"               | python /home/tian/mambaforge/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-linear.fna
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues
Or send an email to virsorter2 near gmail.com if you do not use GitHub

i met this problem, when i run test.fa. could you please help me ? thanks very much!
![4196757626](https://github.com/jiarong/VirSorter2/assets/159194528/7110b009-d0bf-4779-949e-378f566cc773)

**Comment by jiarong** [comment]
Hi, there is some issue with `8seq.fa`. You can double check it's fasta format. Or you can just download the file again and make sure the download is successful.
