### ISSUE TITLE
Error after step 1

### ISSUE THREAD

**Issue by nduan1** [jiarong/VirSorter2#20]
(base) -bash-4.2$ virsorter run -w /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.out -i /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.fa -j 4
[2020-11-23 11:53 INFO] conig file written to /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.out/config.yaml

[2020-11-23 11:53 INFO] Executing: snakemake --snakefile /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/Snakefile --directory /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.out --jobs 4 --configfile /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.out/config.yaml --conda-prefix /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/conda_envs --rerun-incomplete --use-conda --nolock --latency-wait 600   --quiet  all   
Job counts:
	count	jobs
	1	all
	1	circular_linear_split
	1	classify
	5	classify_by_group
	5	classify_full_and_part_by_group
	1	combine_linear_circular
	5	combine_linear_circular_by_group
	1	extract_feature
	1	extract_provirus_seqs
	1	finalize
	1	gff_feature
	5	gff_feature_by_group
	5	hmm_features_by_group
	1	hmm_sort_to_best_hit_taxon
	5	hmm_sort_to_best_hit_taxon_by_group
	1	merge_classification
	1	merge_full_and_part_classification
	5	merge_hmm_gff_features_by_group
	5	merge_provirus_call_by_group_by_split
	1	merge_provirus_call_from_groups
	5	merge_split_hmmtbl
	25	merge_split_hmmtbl_by_group
	25	merge_split_hmmtbl_by_group_tmp
	1	pick_viral_fullseq
	1	preprocess
	1	split_faa
	5	split_faa_by_group
	5	split_gff_by_group
	120
[2020-11-23 11:58 INFO] # of seqs < 0 bp and removed: 0
[2020-11-23 11:58 INFO] # of circular seqs: 1
[2020-11-23 11:58 INFO] # of linear seqs  : 8
[2020-11-23 11:58 INFO] Finish spliting linear contig file with common rbs
[2020-11-23 11:58 INFO] Finish spliting linear contig file with NCLDV rbs
[2020-11-23 11:58 INFO] Finish spliting circular contig file with common rbs
[2020-11-23 11:58 INFO] Finish spliting circular contig file with NCLDV rbs
[2020-11-23 11:58 INFO] Step 1 - preprocess finished.
Traceback (most recent call last):
  File "/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/split-gff-even-seqnum-per-file.py", line 76, in <module>
    main()
  File "/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/split-gff-even-seqnum-per-file.py", line 50, in main
    os.makedirs(outdir, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
[Mon Nov 23 12:01:36 2020]
[Mon Nov 23 12:01:36 2020]
Error in rule split_gff_by_group:
    jobid: 107
    output: iter-0/RNA/all.pdg.gff.splitdir
    shell:
        
            python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/split-gff-even-seqnum-per-file.py iter-0/RNA/all.pdg.gff iter-0/RNA/all.pdg.gff.splitdir 1000
            
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

^C[Mon Nov 23 12:03:36 2020]
Error in rule hmmsearch:
    jobid: 197
    output: iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl
    log: iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.hmm.log (check log file(s) for error message)
    conda-env: /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/conda_envs/69fc02ec
[Mon Nov 23 12:03:36 2020]
    shell:
        
        Domain=Viruses
        if [ $Domain = "Viruses" ]; then
            Hmmdb=/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/hmm/viral/combined.hmm
        else
            Hmmdb=/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/hmm/pfam/Pfam-A-Viruses.hmm
        fi

        Bname=$(basename iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split)
        To_scratch=false
        # move the heavy IO of hmmsearch in local scratch if possible
        if [ -d "/tmp" ]; then
            # not sure df or du are compatible in all linux; use "||To_scratch=false" 
            #   to prevent imcompatibility in some linux distro
            Tmp=$(mktemp -d /tmp/vs2-XXXXXXXXXXXX) && To_scratch=true || To_scratch=false
            Avail=$(df -P /tmp | awk 'END{print $4}') || To_scratch=false
            Fsize=$(du -k iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split | awk '{print $1*5}') || To_scratch=false
            if [ "$Avail" -gt "$Fsize" ] && [ "$To_scratch" = "true" ]; then
                cp iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split $Tmp/$Bname || To_scratch=false
            else
                To_scratch=false
            fi
        fi
        if [ "$To_scratch" = false ]; then
            # local scratch not set or not enough space in local scratch
            hmmsearch -T 30 --tblout iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl --cpu 1 --noali -o /dev/null $Hmmdb iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split 2> iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.hmm.log || { echo "See error details in iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.hmm.log" | python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/echo.py --level error; exit 1; }
        else
            # when To_scratch is true, Tmp and Bname should have been defined successfully
            hmmsearch -T 30 --tblout iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl --cpu 1 --noali -o /dev/null $Hmmdb $Tmp/$Bname 2> iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.hmm.log || { echo "See error details in iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.hmm.log" | python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/echo.py --level error; exit 1; }
            rm -f $Tmp/$Bname && rmdir $Tmp
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Error in rule hmmsearch_by_group:

    jobid: 247
    output: iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl
    log: iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmm.log (check log file(s) for error message)
    conda-env: /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/conda_envs/69fc02ec
    shell:
        
        Domain=Viruses
        Group_specific_hmmdb=/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/group/NCLDV/customized.hmm
        Rbs_pdg_db=/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/group/NCLDV/rbs-prodigal-train.db

        if [ $Domain = "Viruses" ]; then
            if [ -s $Group_specific_hmmdb ]; then
                Hmmdb=$Group_specific_hmmdb
            else
                Hmmdb=/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/hmm/viral/combined.hmm
            fi
        else
            Hmmdb=/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/hmm/pfam/Pfam-A-Viruses.hmm
        fi

        if [ -s $Rbs_pdg_db ] || [ -s $Group_specific_hmmdb ]; then
            To_scratch=false
            Bname=$(basename iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split)
            # move the heavy IO of hmmsearch in local scratch
            if [ -d "/tmp" ]; then
                # not sure df or du are compatible in all linux; use "||To_scratch=false" 
                #   to prevent imcompatibility in some linux distro
                Tmp=$(mktemp -d /tmp/vs2-XXXXXXXXXXXX) && To_scratch=true || To_scratch=false
                Avail=$(df -P /tmp | awk 'END{print $4}') || To_scratch=false
                Fsize=$(du -k iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split | awk '{print $1*5}') || To_scratch=false
                if [ "$Avail" -gt "$Fsize" ] && [ "$To_scratch" = "true" ]; then
                    cp iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split $Tmp/$Bname || To_scratch=false
                else
                    To_scratch=false
                fi
            fi
            if [ "$To_scratch" = false ]; then
                # local scratch not set or not enough space in local scratch
                hmmsearch -T 30 --tblout iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl --cpu 1 --noali -o /dev/null $Hmmdb iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split 2> iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmm.log || { echo "See error details in iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmm.log" | python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/echo.py --level error; exit 1; }
            else
                # when To_scratch is true, Tmp and Bname should have been defined successfully
                hmmsearch -T 30 --tblout iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl --cpu 1 --noali -o /dev/null $Hmmdb $Tmp/$Bname 2> iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmm.log || { echo "See error details in iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmm.log" | python /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/echo.py --level error; exit 1; }
                rm -f $Tmp/$Bname && rmdir $Tmp
            fi
        else
            touch iter-0/NCLDV/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Could you help me with ths? Thanks!

**Comment by nduan1** [comment]
I tried to remove the "exist_ok=True" arguement in os.makedirs(outdir, exist_ok=True) in the file:
/lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/./scripts/split-gff-even-seqnum-per-file.py, it works.
(base) -bash-4.2$ virsorter run -i /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/test.fa -j 4
[2020-11-23 12:29 INFO] conig file written to /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/config.yaml

[2020-11-23 12:29 INFO] Executing: snakemake --snakefile /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/VirSorter2/virsorter/Snakefile --directory /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test --jobs 4 --configfile /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/virsorter_test/config.yaml --conda-prefix /lustre/haven/proj/UTK0124/conda2/envs/vs2/bin/conda_envs --rerun-incomplete --use-conda --nolock --latency-wait 600   --quiet  all   
Job counts:
	count	jobs
	1	all
	1	circular_linear_split
	1	classify
	5	classify_by_group
	5	classify_full_and_part_by_group
	1	combine_linear_circular
	5	combine_linear_circular_by_group
	1	extract_feature
	1	extract_provirus_seqs
	1	finalize
	1	gff_feature
	5	gff_feature_by_group
	5	hmm_features_by_group
	1	hmm_sort_to_best_hit_taxon
	5	hmm_sort_to_best_hit_taxon_by_group
	1	merge_classification
	1	merge_full_and_part_classification
	5	merge_hmm_gff_features_by_group
	5	merge_provirus_call_by_group_by_split
	1	merge_provirus_call_from_groups
	5	merge_split_hmmtbl
	25	merge_split_hmmtbl_by_group
	25	merge_split_hmmtbl_by_group_tmp
	1	pick_viral_fullseq
	1	preprocess
	1	split_faa
	5	split_faa_by_group
	5	split_gff_by_group
	120
[2020-11-23 12:29 INFO] # of seqs < 0 bp and removed: 0
[2020-11-23 12:29 INFO] # of circular seqs: 1
[2020-11-23 12:29 INFO] # of linear seqs  : 8
[2020-11-23 12:29 INFO] Finish spliting linear contig file with common rbs
[2020-11-23 12:29 INFO] Finish spliting linear contig file with NCLDV rbs
[2020-11-23 12:29 INFO] Finish spliting circular contig file with common rbs
[2020-11-23 12:29 INFO] Finish spliting circular contig file with NCLDV rbs
[2020-11-23 12:29 INFO] Step 1 - preprocess finished.
[2020-11-23 12:50 INFO] Step 2 - extract-feature finished.
[2020-11-23 12:51 INFO] 
            ====> VirSorter run (provirus mode) finished.
            # of full    seqs (>=2 genes) as viral:	6
            # of partial seqs (>=2 genes) as viral:	1
            # of short   seqs (< 2 genes) as viral:	1

            Useful output files:
            final-viral-score.tsv       ==> score table
            final-viral-combined.fa     ==> all viral seqs
            final-viral-boundary.tsv    ==> table with boundary info
            
            Suffix is added to seq names in final-viral-combined.fa:
            full    seqs (>=2 genes) as viral:	||full
            partial seqs (>=2 genes) as viral:	||partial
            short   seqs (< 2 genes) as viral:	||lt2gene

            NOTES:
            Users can further screen the results based on the following 
                columns in final-viral-score.tsv:
                - contig length (length) 
                - hallmark gene count (hallmark)
                - viral gene % (viral) 
                - cellular gene % (cellular)
            The group field in final-viral-score.tsv should NOT be used
                as reliable taxonomy info

            <====
            
[2020-11-23 12:51 INFO] Step 3 - classify finished

I think it should be fine at this time, but it could be better to let the @jiarong double-check this issue. Thanks!

**Comment by jiarong** [comment]
Thanks for the notice. "exist=True" is only available for python 3.2 or high. I will fix this in the installation guide.
