### ISSUE TITLE
Validation of Database Fetching

### ISSUE THREAD

**Issue by ChristosMatzoros** [jiarong/VirSorter2#203]
Dear VS2 Team,

Is there a fast way to validate that the database has the expected structure after the downloading phase? I see there is an empty file called `Done_all_setup`. Is this file created only if the database is built correctly?

Thank you!

**Comment by jiarong** [comment]
There is many files are directories in it, so manual checking is not a good idea. It's correct that `Done_all_setup` is created only after the database is built. If the database setup is not successful, you should see error message from the command line.
