### ISSUE TITLE
Compatibility issue of scikit-learn 0.22.1 with python 3.9 in virsorter run

### ISSUE THREAD

**Issue by ChristosMatzoros** [jiarong/VirSorter2#207]
Hello,

In my environment, I have to strictly use python 3.9 and to have all the dependencies installed before any execution (either with `setup` or `run`). 
What I am trying to do is to install from bioconda and add the dependencies needed from the development version. I do that in order to be able to use the `-s` option in `virsorter setup` and the option `--use-conda-off` in `virsorter run`.

There is a compatibility problem with `python3.9` and `scikit-learn 0.22.1` if I want to use this option. is there a workaround to make it work with `python3.9`?

Furthermore, from the installation command of development version:
`mamba create -n vs2 -c conda-forge -c bioconda "python>=3.6,<=3.10" scikit-learn=0.22.1 imbalanced-learn pandas seaborn hmmer==3.3 prodigal screed ruamel.yaml "snakemake>=5.18,<=5.26" click "conda-package-handling<=1.9"`

The `"python>=3.6,<=3.10"` isn't correct as it will not work for 3.9. Am I missing something?

Is there a way to install everything before any execution (of `setup` or `run`) in an environment with `python3.9`?

Thank you

**Comment by jiarong** [comment]
Hi, you can 1) check out the [container option](https://github.com/jiarong/VirSorter2?tab=readme-ov-file#option-3), or 2) experiment with other scikit-learn version. Similar versions might give warnings but should still work.
