### ISSUE TITLE
The 'final-viral-combined-for-dramv.fa' file contains sequences with the same ID

### ISSUE THREAD

**Issue by llechoecho** [jiarong/VirSorter2#210]
Hi,
When I was running the DRAM-v.py annotate, I encountered an error message 'File exists: 'subset15/working_dir/VIR6T3_k141_86934-cat_4'' which caused the program to fail. Upon checking, I found that there are two sequences with the same ID in the 'final-viral-combined-for-dramv.fa' file. These two sequences are two partial sequences from the same sequence. What can I do to resolve this issue?
Thank you.

**Comment by jiarong** [comment]
Sorry for the late reply. I was super busy last week.  To ensure two prophage from one sequence has different names, make sure you do NOT add ` --seqname-suffix-off` flag.

**Comment by llechoecho** [comment]
Got it, I'll remove the parameter and try to run it again, thanks for the reply.
