### ISSUE TITLE
CreateCondaEnvironmentException: Could not create conda environment

### ISSUE THREAD

**Issue by JCHmu** [jiarong/VirSorter2#214]
When I run the virsorter run -w vs2 -i CRC_meta.fa --min-length 1500 -j 4 all code again, I get an error as CreateCondaEnvironmentException.
Could not create conda environment 

CreateCondaEnvironmentException:
Could not create conda environment from /data1/jch/miniconda3/envs/virsorter/lib/python3.10/site-packages/virsorter/rules/../envs/vs2.yaml:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/data1/jch/miniconda3/envs/virsorter/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/data1/jch/miniconda3/envs/virsorter/lib/python3.10/site-packages/conda_env/cli/main.py", line 56, in do_call
        exit_code = getattr(module, func_name)(arguments, parser)
      File "/data1/jch/miniconda3/envs/virsorter/lib/python3.10/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
      File "/data1/jch/miniconda3/envs/virsorter/lib/python3.10/site-packages/conda_env/cli/main_create.py", line 162, in execute
        result[installer_type] = installer.install(
      File "/data1/jch/miniconda3/envs/virsorter/lib/python3.10/site-packages/mamba/mamba_env.py", line 54, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/data1/jch/miniconda3/envs/virsorter/lib/python3.10/site-packages/mamba/utils.py", line 126, in load_channels
        index = get_index(
      File "/data1/jch/miniconda3/envs/virsorter/lib/python3.10/site-packages/mamba/utils.py", line 107, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Download error (28) Timeout was reached [https://repo.anaconda.com/pkgs/r/noarch/repodata.json.zst]
    Failed to resolve host 'repo.anaconda.com' with timeout after 43149 ms

`$ /data1/jch/miniconda3/envs/virsorter/bin/mamba create --quiet --file /data1/jch/db/virsorter_db/db/conda_envs/b1c7c643.yaml --prefix /data1/jch/db/virsorter_db/db/conda_envs/b1c7c643`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
   CONDA_BACKUP_ADDR2LINE=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          addr2line
          CONDA_BACKUP_AR=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-ar
          CONDA_BACKUP_AS=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-as
       CONDA_BACKUP_BUILD=x86_64-conda-linux-gnu
          CONDA_BACKUP_CC=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-cc
CONDA_BACKUP_CC_FOR_BUILD=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-cc
      CONDA_BACKUP_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          strong -fno-plt -O2 -ffunction-sections -pipe -isystem
                          /data1/jch/miniconda3/envs/deepvirfinder/include -march=nocona
                          -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-
                          plt -O2 -ffunction-sections -pipe -isystem
                          /data1/jch/miniconda3/envs/deepvirfinder/include
CONDA_BACKUP_CMAKE_PREFIX_PATH=/data1/jch/miniconda3/envs/deepvirfinder:/data1/jch/miniconda3/envs/de
                          epvirfinder/x86_64-conda-linux-gnu/sysroot/usr
CONDA_BACKUP_CONDA_BUILD_SYSROOT=/data1/jch/miniconda3/envs/deepvirfinder/x86_64-conda-linux-
                          gnu/sysroot
CONDA_BACKUP_CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
CONDA_BACKUP_CONDA_TOOLCHAIN_HOST=x86_64-conda-linux-gnu
         CONDA_BACKUP_CPP=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          cpp
    CONDA_BACKUP_CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem
                          /data1/jch/miniconda3/envs/deepvirfinder/include -DNDEBUG
                          -D_FORTIFY_SOURCE=2 -O2 -isystem
                          /data1/jch/miniconda3/envs/deepvirfinder/include
         CONDA_BACKUP_CXX=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-
                          gnu-c++
     CONDA_BACKUP_CXXFILT=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-
                          gnu-c++filt
    CONDA_BACKUP_CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona
                          -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-
                          plt -O2 -ffunction-sections -pipe -isystem
                          /data1/jch/miniconda3/envs/deepvirfinder/include -fvisibility-inlines-
                          hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-
                          vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-
                          sections -pipe -isystem
                          /data1/jch/miniconda3/envs/deepvirfinder/include
CONDA_BACKUP_CXX_FOR_BUILD=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-
                          gnu-c++
CONDA_BACKUP_DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-
                          all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments
                          -ffunction-sections -pipe -isystem
                          /data1/jch/miniconda3/envs/deepvirfinder/include -march=nocona
                          -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt
                          -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections
                          -pipe -isystem /data1/jch/miniconda3/envs/deepvirfinder/include
CONDA_BACKUP_DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem
                          /data1/jch/miniconda3/envs/deepvirfinder/include -D_DEBUG
                          -D_FORTIFY_SOURCE=2 -Og -isystem
                          /data1/jch/miniconda3/envs/deepvirfinder/include
CONDA_BACKUP_DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona
                          -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt
                          -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections
                          -pipe -isystem /data1/jch/miniconda3/envs/deepvirfinder/include
                          -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona
                          -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt
                          -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections
                          -pipe -isystem /data1/jch/miniconda3/envs/deepvirfinder/include
         CONDA_BACKUP_DWP=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          dwp
     CONDA_BACKUP_ELFEDIT=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          elfedit
         CONDA_BACKUP_GCC=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          gcc
      CONDA_BACKUP_GCC_AR=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          gcc-ar
      CONDA_BACKUP_GCC_NM=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          gcc-nm
  CONDA_BACKUP_GCC_RANLIB=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          gcc-ranlib
       CONDA_BACKUP_GPROF=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          gprof
         CONDA_BACKUP_GXX=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-
                          gnu-g++
        CONDA_BACKUP_HOST=x86_64-conda-linux-gnu
          CONDA_BACKUP_LD=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-ld
     CONDA_BACKUP_LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,
                          --disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined
                          -Wl,-rpath,/data1/jch/miniconda3/envs/deepvirfinder/lib -Wl,-rpath-
                          link,/data1/jch/miniconda3/envs/deepvirfinder/lib
                          -L/data1/jch/miniconda3/envs/deepvirfinder/lib -Wl,-O2 -Wl,--sort-
                          common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags
                          -Wl,--gc-sections -Wl,--allow-shlib-undefined
                          -Wl,-rpath,/data1/jch/miniconda3/envs/deepvirfinder/lib -Wl,-rpath-
                          link,/data1/jch/miniconda3/envs/deepvirfinder/lib
                          -L/data1/jch/miniconda3/envs/deepvirfinder/lib
     CONDA_BACKUP_LD_GOLD=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          ld.gold
  CONDA_BACKUP_MESON_ARGS=--buildtype release
          CONDA_BACKUP_NM=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-nm
     CONDA_BACKUP_OBJCOPY=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          objcopy
     CONDA_BACKUP_OBJDUMP=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          objdump
      CONDA_BACKUP_RANLIB=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          ranlib
     CONDA_BACKUP_READELF=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          readelf
        CONDA_BACKUP_SIZE=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          size
     CONDA_BACKUP_STRINGS=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          strings
       CONDA_BACKUP_STRIP=/data1/jch/miniconda3/envs/deepvirfinder/bin/x86_64-conda-linux-gnu-
                          strip
CONDA_BACKUP__CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
 CONDA_BACKUP_build_alias=x86_64-conda-linux-gnu
  CONDA_BACKUP_host_alias=x86_64-conda-linux-gnu
        CONDA_DEFAULT_ENV=virsorter
                CONDA_EXE=/data1/jch/miniconda3/bin/conda
             CONDA_PREFIX=/data1/jch/miniconda3/envs/virsorter
           CONDA_PREFIX_1=/data1/jch/miniconda3
           CONDA_PREFIX_2=/data1/jch/miniconda3/envs/deepvirfinder
           CONDA_PREFIX_3=/data1/jch/miniconda3/envs/vs2
           CONDA_PREFIX_4=/data1/jch/miniconda3
    CONDA_PROMPT_MODIFIER=(virsorter)
         CONDA_PYTHON_EXE=/data1/jch/miniconda3/bin/python
               CONDA_ROOT=/data1/jch/miniconda3/envs/virsorter
              CONDA_SHLVL=5
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/data1/jch/miniconda3/envs/virsorter/bin:/data1/jch/miniconda3/condabi
                          n:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/ga
                          mes:/usr/local/games:/snap/bin:/data1/jch/db/EasyMicrobiome/linux:/dat
                          a1/jch/db/EasyMicrobiome/script:/data1/jch/db/EasyMicrobiome
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /data1/jch/miniconda3/envs/virsorter
            shell level : 5
       user config file : /home/jch/.condarc
 populated config files : /home/jch/.condarc
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.10.0.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.4=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /data1/jch/miniconda3/envs/virsorter  (writable)
      conda av data dir : /data1/jch/miniconda3/envs/virsorter/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data1/jch/miniconda3/envs/virsorter/pkgs
                          /home/jch/.conda/pkgs
       envs directories : /data1/jch/miniconda3/envs/virsorter/envs
                          /home/jch/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.32.3 CPython/3.10.0 Linux/5.15.0-70-generic ubuntu/20.04.5 glibc/2.35
                UID:GID : 1003:1001
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

  File "/data1/jch/miniconda3/envs/virsorter/lib/python3.10/site-packages/snakemake/deployment/conda.py", line 350, in create

**Comment by yyyangzd** [comment]
Hi, I encountered the same error. Could you please tell me how to solve the problem? Thanks!

**Comment by brilliant2643** [comment]
> Hi, I encountered the same error. Could you please tell me how to solve the problem? Thanks!

Me too! Waiting for an answer. Thanks a lot!

**Comment by chopinone** [comment]
same，how to slove it ,pleased!!!!
