### ISSUE TITLE
Questions about prepare4dramv

### ISSUE THREAD

**Issue by chenyj8** [jiarong/VirSorter2#217]
Hi,

I turn on the "--prep-for-dramv" option to produce the files for DRAM-v annotation. Note that the input fasta file contains viral contigs obtained from different viral identification tools (including virsorter2). I only used virsorter2 to produce the files for DRAM-v without identifying the viral contigs in my input fasta files.

My code is:

`virsorter run
-i ncbi_refseq_virus_rename.fasta
-w refseq4dramv
--include-groups "dsDNAphage,ssDNA"
--seqname-suffix-off
--viral-gene-enrich-off
--provirus-off
--prep-for-dramv
--keep-original-seq
--min-score 0
-j 94
all `

However, the log file shows that the input file contains 18,670 contigs but there are only 13,776 contigs in the output fasta. I have set "--viral-gene-enrich-off" and "--min-score 0", why are so many contigs still removed by virosrter2?

[2024-09-22 23:53 INFO] # of seqs < 0 bp and removed: 0
[2024-09-22 23:53 INFO] # of circular seqs: 928
[2024-09-22 23:53 INFO] # of linear seqs  : 17742
[2024-09-22 23:53 INFO] Finish spliting circular contig file with common rbs
[2024-09-22 23:53 INFO] Finish spliting linear contig file with common rbs
[2024-09-22 23:58 INFO] Step 1 - preprocess finished.
[2024-09-23 02:47 INFO] Step 2 - extract-feature finished.
[2024-09-23 03:34 INFO] 
            ====> VirSorter run (non-provirus mode) finished.
            # of contigs w/ >=2 genes as viral: 13618
            # of contigs w/ < 2 genes as viral: 158

Useful output files:
final-viral-score.tsv      ==> score table
final-viral-combined.fa    ==> all viral seqs
for-dramv                  ==> dir with input files for dramv

**Comment by jiarong** [comment]
Hi, this is expected. VS2 discards contigs with < 2 genes without hallmark genes at very beginning.

**Comment by chenyj8** [comment]
> Hi, this is expected. VS2 discards contigs with < 2 genes without hallmark genes at very beginning.

Thanks for the explanation.
