### ISSUE TITLE
How to parallel execution on Slurm cluster?

### ISSUE THREAD

**Issue by KateSakharova** [jiarong/VirSorter2#218]
Hello,

I'm running Virsorter2 on Slurm cluster as a nextflow process. I can request many threads for it but it seems running very slow and do not parallel jobs. 

What arguments should I adjust in order to speed up it and use all requested threads for that process?
Lets say, I have 16 requested threads for Virsorter2, how should I adjust GENERAL_THREADS, HMMSEARCH_THREADS, CLASSIFY_THREADS? or there are other agruments to look at?
Thank you!

Best,
Kate

**Comment by jiarong** [comment]
Hi, you can split the input data and run each split in parallel.

**Comment by KateSakharova** [comment]
@jiarong 
Thank you for reply! 
Do I undertand correctly this snakemake pipeline is not able to submit multiple jobs for execution? It still would be 1 job on cluster? 
Best,
Kate

**Comment by jiarong** [comment]
It can submit each rule within it as a cluster job using the standard "--cluster" option. I am not sure how the cluster resources can be managed within nextflow tho.
