### ISSUE TITLE
Question about criteria for prophages extraction

### ISSUE THREAD

**Issue by KateSakharova** [jiarong/VirSorter2#219]
Hello,

1) As far as I understand correctly, `full` sequences can also be prophages? Is there a way to extract those from VirSorter2 outputs? 

2) What criteria is better to use for viruses to separate those into **high confident** viruses and **low confident** viruses?

Best,
Kate

**Comment by jiarong** [comment]
Sorry, I did not notice this issue till just now.
1. "full" suggests the whole sequence looks viral, but it just could just be a fragment from prophage. It's difficult to tell if a "full" sequence is prophage. The full sequences should have "__full" as suffix in their sequence id.
2. viral hallmark genes.
