### ISSUE TITLE
VirSorter2 installs README.md and LICENSE under python root

### ISSUE THREAD

**Issue by ryneches** [jiarong/VirSorter2#24]
VirSorter2 installs README.md and LICENSE at the root of your python environment. For example, if you install VirSorter2 system wide, it will place README.md and LICENSE in /usr/README.md and /usr/LICENSE. These files are usually not installed with the package, as far as I know.

**Comment by jiarong** [comment]
@ryneches, good catch. I will fix in next release.

**Comment by jiarong** [comment]
Fixed in release 2.1
