### ISSUE TITLE
virsorter2 results

### ISSUE THREAD

**Issue by javadgh6** [jiarong/VirSorter2#34]
Dear  Developer,

Do you have any suggestion for taxonomic classification of virsorter2 predicted viral sequences??

**Comment by jiarong** [comment]
vContact2 is recommended for dsDNA phages. I am not sure about RNA and ssDNA viruses. Suggestions are welcomed.

**Comment by maocheng2020** [comment]
> vContact2 is recommended for dsDNA phages. I am not sure about RNA and ssDNA viruses. Suggestions are welcomed.

I have a small problem, virsorter output file format is nucleic acid sequence, vContact2 input file format need protein sequence, with Prodigal prediction? But Prodigal is mainly used for the prediction of bacteria archaea, can viruses also?thanks.

**Comment by jiarong** [comment]
Right, Prodigal is designed for prokaryotes, but it works pretty well for viruses too in our experience.
