### ISSUE TITLE
step3-classify error (could not convert string to float)

### ISSUE THREAD

**Issue by TsumaR** [jiarong/VirSorter2#35]
Hi,
Thank you very much for developing such a great tool.
I ran Virsorter2 on several samples and it worked for most of them, but not for some of the FASTA files.
In the `step3-classify/pick-viral-fullseq.log` file, I found the following error.

```
Traceback (most recent call last):
  File "/home/〇〇/pick-viral-contig-from-clf.py", line 64, in <module>
    main()
  File "/home/〇〇/pick-viral-contig-from-clf.py", line 37, in main
    proba_lis = [float(i) for i in lis[1:]]
  File "/home/〇〇/pick-viral-contig-from-clf.py", line 37, in <listcomp>
    proba_lis = [float(i) for i in lis[1:]]
ValueError: could not convert string to float: 'NODE_120_length_1203_cov_2.03571'
```
NODE_120_length_1203_cov_2.03571 is contig name.
I hope you can help me with a solution.
best

**Comment by jiarong** [comment]
Can you share `iter-0/all-fullseq-proba.tsv` in the output directory?

**Comment by TsumaR** [comment]
I don't have `iter-0/all-fullseq-proba.tsv` in my output directory.
In output directory, only the below files exist.
```
Done-extract-feature  Done-preprocess  config.yaml  log
```
In the log directory, I have `iter-0` directory which contains the below directories.
```
step1-pp  step2-extract-feature  step3-classify
```
`step3-classify` directory is like this.

```
   0  1月  7 23:12 all-score-NCLDV.log
   0  1月  7 23:12 all-score-RNA.log
   0  1月  7 23:11 all-score-dsDNAphage.log
   0  1月  7 23:11 all-score-lavidaviridae.log
   0  1月  7 23:12 all-score-merge.log
   0  1月  7 23:11 all-score-ssDNA.log
 565  1月  7 23:13 pick-viral-fullseq.log
```

I apologize for the inconvenience for you,
best

**Comment by jiarong** [comment]
What was the command line you used?

**Comment by dwwaite** [comment]
Hello,

I've just encountered the same problem, was there a solution to this issue? If you need the information, my exact error was:

```bash
Traceback (most recent call last):
  File "/home/david/vir_pipelines/VirSorter2/virsorter/./scripts/pick-viral-contig-from-clf.py", line 64, in <module>
    main()
  File "/home/david/vir_pipelines/VirSorter2/virsorter/./scripts/pick-viral-contig-from-clf.py", line 37, in main
    proba_lis = [float(i) for i in lis[1:]]
  File "/home/david/vir_pipelines/VirSorter2/virsorter/./scripts/pick-viral-contig-from-clf.py", line 37, in <listcomp>
    proba_lis = [float(i) for i in lis[1:]]
ValueError: could not convert string to float: 'X06390.1'
```

And the contents of iter-0/all-fullseq-proba.tsv is:

```
dsDNAphage      seqname NCLDV   RNA     ssDNA   lavidaviridae
NaN     X06390.1        0.000   NaN     NaN     NaN
```

Regards,
David

**Comment by jiarong** [comment]
@dwwaite Could you share the sequence, "X06390.1", to help me reproduce the error?

**Comment by jiarong** [comment]
@dwwaite I think I figured out what the issue is. Check out the development version.

**Comment by dwwaite** [comment]
@jiarong Great, that worked perfectly. Thanks a lot!
