### ISSUE TITLE
another way to prepare database

### ISSUE THREAD

**Issue by liupfskygre** [jiarong/VirSorter2#36]
Hi, 
    I am trying to prepare the database for virsorter2, with 
```
virsorter setup -d db -j 4
```

but my net is not working properly due to firewall issue,
```
Server not responding ...
```
do we have another way to download all possible db files and compile them? 

like download them separately and do setup. 

thanks.

**Comment by jiarong** [comment]
Hi, thanks for the feedback. I have added another way to do the setup manually. Check it out in the README file.

**Comment by liupfskygre** [comment]
that's cool, well try it! thanks
