### ISSUE TITLE
classification Error? 

### ISSUE THREAD

**Issue by eawebb** [jiarong/VirSorter2#4]
hi jiarong,

This new version looks really exciting (recommended to me by matt), and i have been able to run the test dataset to finish.  i used the new conda install that you suggested in the other issue, plus the old one in the read me (adding conda screed).  it is running on a centos HPC.  it gets towards what i think is the end of the job when it is trying to collate the summary data files and crashes.  

my command was:
virsorter run -w vs2_results_7_25/st19.out -i /scratch/eawebb/rough_megahit_contigs/output_st19_final.contigs.fa --provirus-off --max-orf-per-seq 20 --min-length 700 --include-groups "dsDNAphage,ssDNA,RNA"  -j 24

and the error log is below (this was the command that was calling up screed in my previous error).

> [2020-07-25 15:49 INFO] conig file written to /scratch/eawebb/vs2_results_7_25/st19.out/config.yaml
> 
> [2020-07-25 15:49 INFO] Executing: snakemake --snakefile /scratch/eawebb/miniconda/envs/vs2/lib/python3.8/site-packages/virsorter/Snakefile --directory /scratch/eawebb/vs2_results_7_25/st19.out --jobs 24 --configfile /scratch/eawebb/vs2_results_7_25/st19.out/config.yaml --conda-prefix /scratch/eawebb/db/conda_envs --rerun-incomplete --use-conda --nolock --latency-wait 600   --quiet  all
> Job counts:
> 	count	jobs
> 	1	all
> 	1	classify
> 	1	finalize
> 	3
> *** Usage: python add-suffix-seqname-keep-desc.py <contig.fa> suffix
> /usr/bin/bash: full: command not found
> [Sat Jul 25 15:49:18 2020]
> Error in rule finalize:
>     jobid: 8
>     output: final-viral-combined.fa, final-viral-score.tsv
>     shell:
> 
>             python /scratch/eawebb/miniconda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/add-suffix-seqname-keep-desc.py iter-0/viral-fullseq.fa ||full > final-viral-combined.fa
>             python /scratch/eawebb/miniconda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/add-suffix-seqname-keep-desc.py iter-0/viral-lt2gene-w-hallmark.fa ||lt2gene >> final-viral-combined.fa
>             cp iter-0/all-fullseq-proba.tsv final-viral-score.tsv
>             N_viral_fullseq=$(grep -c '^>' iter-0/viral-fullseq.fa || :)
>             N_viral_lt2gene=$(grep -c '^>' iter-0/viral-lt2gene-w-hallmark.fa || :)
>             echo -e "
>             ====> VirSorter run (non-provirus mode) finished.
>             # of viral contigs:	$N_viral_fullseq
>             # of short viral contigs (<2 genes):	$N_viral_lt2gene
> 
>             Useful output files:
>             final-viral-score.tsv
>             final-viral-combined.fa
>             <====
>             " | python /scratch/eawebb/miniconda/envs/vs2/lib/python3.8/site-packages/virsorter/./scripts/echo.py
> 
>         (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
> 
> Exiting because a job execution failed. Look above for error message
> [2020-07-25 15:49 CRITICAL] Command 'snakemake --snakefile /scratch/eawebb/miniconda/envs/vs2/lib/python3.8/site-packages/virsorter/Snakefile --directory /scratch/eawebb/vs2_results_7_25/st19.out --jobs 24 --configfile /scratch/eawebb/vs2_results_7_25/st19.out/config.yaml --conda-prefix /scratch/eawebb/db/conda_envs --rerun-incomplete --use-conda --nolock --latency-wait 600   --quiet  all   ' returned non-zero exit status 1.
> 

Thanks 
eric

**Comment by jiarong** [comment]
fixed
