### ISSUE TITLE
Formatting issue for DRAMv inputs

### ISSUE THREAD

**Issue by Puumanamana** [jiarong/VirSorter2#59]
Hi,

I'm not sure whether I should open the issue on the DRAM GitHub or virsorter2, but my first feeling is that my issue is related to virsorter. I'm trying to run DRAMv to annotate my contigs, but DRAMv keeps failing. It seems something is wrong with the input generated by Virsorter2 (the .tab and .fasta look like they sometimes add a different suffix to the contigs). I followed this [workflow](https://www.protocols.io/view/viral-sequence-identification-sop-with-virsorter2-btv8nn9w?step=5) to generate the inputs for DRAMv. I ran the following commands:

```
$ virsorter run -j 20 --include-groups dsDNAphage,NCLDV,RNA,ssDNA,lavidaviridae \
        --min-length 5000 --min-score 0.5 \
        --seqname-suffix-off --viral-gene-enrich-off --prep-for-dramv \
        -i checkv/combined.fna -w vs2-pass2 \
        all
$ DRAM-v.py annotate \                                                                                                                                                                   
    -i vs2-pass2/for-dramv/final-viral-combined-for-dramv.fa \
    -v vs2-pass2/for-dramv/viral-affi-contigs-for-dramv.tab \                                                                                                                              
    -o dramv-annotate \
    --skip_trnascan --threads 60 --min_contig_size 5000                                                                                                                                    
```

DRAMv returns this error rather quickly:
```
2021-04-20 22:24:00.094684: Viral annotation started
Traceback (most recent call last):
  File "~/.miniconda3/envs/DRAM/bin/DRAM-v.py", line 140, in <module>
    args.func(**args_dict)
  File "~/.miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_vgfs.py", line 395, in annotate_vgfs
    raise ValueError("No virsorter calls found in %s for scaffold %s from input fasta" %
ValueError: No virsorter calls found in vs2-pass2/for-dramv/viral-affi-contigs-for-dramv.tab for scaffold NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__0_partial-cat_1 from input fasta
```

If it can be of any help, the corresponding entries in both final-viral-combined-for-dramv.fa and viral-affi-contigs-for-dramv.tab are:

**final-viral-combined-for-dramv.fa**
```
>NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__0_partial-cat_1
TTATTCATTC[...]
```
**viral-affi-contigs-for-dramv.tab**
```
>NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028|17|l
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__1|1|552|12916|-|LemA|180.7|-|2|LemA|180.7|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__2|742|2001|12916|-|Peptidase_M42|56.4|-|2|Peptidase_M42|56.4|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__3|2039|2137|12916|+|-|nan|-|2|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__4|2185|2445|12916|+|Phage_cluster_23132.ali_faa|84.8|-|1|Fer4|43.1|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__5|2620|3573|12916|+|-|nan|-|2|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__6|3623|4369|12916|-|-|nan|-|2|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__7|4416|4805|12916|-|-|nan|-|2|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__8|4899|5522|12916|+|-|nan|-|2|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__9|5519|5767|12916|+|-|nan|-|2|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__10|5782|7338|12916|-|Phage_cluster_20880.ali_faa|100.7|-|0|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__11|7368|7565|12916|-|-|nan|-|2|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__12|7534|8949|12916|-|Phage_cluster_1311.ali_faa|100.3|-|1|ABC_tran|30.6|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__13|8969|9451|12916|-|-|nan|-|2|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__14|9679|10596|12916|+|Phage_cluster_667.ali_faa|91.1|-|1|HTH_3|46.6|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__15|10860|11702|12916|+|-|nan|-|2|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__16|11784|12287|12916|-|-|nan|-|2|-|nan|-
NODE_1_length_512008_cov_42_951095_1383CS_MVBS_1028__17|12284|12916|12916|-|-|nan|-|2|-|nan|-
```

Thank you for your help !
Cédric

**Comment by jiarong** [comment]
Hi, I have received the issue from other issues too. I should have been fixed the development version. I will update bioconda version once I fixed another issue I am working on.

**Comment by Puumanamana** [comment]
Thank you, I tried the development version and it works now!

**Comment by YanjieZhu1997** [comment]
> Hi, I have received the issue from other users too. It should have been fixed the development version. I will update bioconda version once I fix another issue I am working on.

Hi Jiarong, thank you for develping this wonderful tool! I'm using the latest virsorter 2.2.4 but the same formatting issue of the viral-affi-contigs-for-dramv.tab still exists.

>vOTU00003__full|152|l
vOTU00003__full__1|202|1083|112053|+|-|nan|-|2|-|nan|-
vOTU00003__full__2|1320|1490|112053|-|-|nan|-|2|-|nan|-
vOTU00003__full__3|1480|1713|112053|-|-|nan|-|2|-|nan|-
vOTU00003__full__4|1713|2282|112053|-|3300000123@KGI_S2_ANT06_2345mDRAFT_c1000006@KGI_S2_ANT06_2345mDRAFT_1000006101|100.7|-|1|-|nan|-
vOTU00003__full__5|2402|4180|112053|+|NP_043560@NC_001706|530.0|-|0|Terminase_1|254.4|-
vOTU00003__full__6|4208|5530|112053|+|Phage_cluster_83.ali_faa|376.6|-|0|Phage_portal|250.2|-
vOTU00003__full__7|5514|6572|112053|+|Phage_cluster_22935.ali_faa|176.8|-|0|Peptidase_S78|70.5|-
vOTU00003__full__8|6708|8081|112053|+|Phage_cluster_44098.ali_faa|233.7|-|0|Phage_capsid|112.3|-
vOTU00003__full__9|8151|8705|112053|+|Phage_cluster_683.ali_faa|142.2|-|0|Phage_connect_1|47.1|-

This leads to the failure of my DRAM-v annotation.
