### ISSUE TITLE
Virsorter2 split the contigs trimmed by checkv 

### ISSUE THREAD

**Issue by yanhui09** [jiarong/VirSorter2#62]
Dear Jiarong,

Thanks for the great tool. I followed the [SOP](https://www.protocols.io/view/viral-sequence-identification-sop-with-virsorter2-btv8nn9w?step=3) to identify the viral contigs in my assemblies. 

Everything was fine but I got one error from DRAM-v, telling me that there're are duplicate contigs during annotation.
I checked the output of checkv and the two rounds of virsorter, and found one long contig (~100k) was split during the second use of virsorter. Interestingly, this contig was not split in the former processing (1st virsorter and checkv).

The checkv shall trim the host sequence at the ends. It seems some host genes mixed in the middle of the viral fragments. So I wonder how I shall evaluate this contig? Shall I split the fragments?  I am also a bit curious about why virsorter output changed after trimming the host ends.

Best regards,
Yan

**Comment by jiarong** [comment]
Hi Yan, thanks for the feedback. The technical reason is probably checkV trimmed host genes along with some unknown genes (likely viral) and the overall VirSorter2 score of the contig drop below the cutoff (0.8 by default) that triggers prophage scanning. This is likely a situation that two prophage located closely with each other in the contig and thus having a high score as a whole contig.  You can use DRAM to look at if the genes in the middle (between the two splits) are host or viral. Calling prophage ends is still a challenging problem and neither VirSorter2 nor checkV are perfect.

**Comment by yanhui09** [comment]
Hi Jiarong

Thanks for the quick response. You are right. :smile: The contig was not split anymore when I switched on the "--provirus-off".
Sorry for one follow-up question. If I switch off the "provirus screening in the second use of visorter2, will it induce any bias? 

From my understanding, the provirus has been screened in the previous process of virsorter2 and checkv, and trimmed by checkv. But the provirus boundary predicted by checkv/virsorter2 is only an estimate. It may be acceptable to stop provirus screening in the 2nd use of virsorter if I want to preserve relatively "complete" contig and validate it later. The main purpose of 2nd visorter is to prepare files for the DRAM-v. Is my understanding correct?

**Comment by jiarong** [comment]
You are right. The "--provirus-off" is a good solution to duplicate name issue. There should be no bias, contig from checkV should be preserved. I will add this option to SOP in next version. Thanks for your feedback again!

**Comment by yanhui09** [comment]
Also thanks for your confirmation. I will close this issue. Super. 🍺
