### ISSUE TITLE
hmmsearch always runs with --cpu 1

### ISSUE THREAD

**Issue by simone-pignotti** [jiarong/VirSorter2#64]
Hi, I noticed that `hmmsearch` always runs with one core, even when `--jobs N` is used. Would it be possible for this command to match the number of threads available to Snakemake? This should speed up step 2 by quite a lot.

Thank you for maintaining this great tool!

Simone

**Comment by simone-pignotti** [comment]
Nevermind, just found the `Hmmsearch_threads` parameter. Sorry for the spam!

**Comment by jiarong** [comment]
Just in case others have the same Q, you can set this parameter in command line: `virsorter config --set HMMSEARCH_THREADS=4`, or just edit it in `template-config.yaml`.
