### ISSUE TITLE
Error during iter_0 classify

### ISSUE THREAD

**Issue by MeggyC** [jiarong/VirSorter2#69]
Hi there, 
I am running VIRSorter 2 in a linux shell and it doesn't finish. 
My command was: 
```
virsorter run -w /work2/microbiome/coral/Accelerate_project/analyses/viral_prep/virsorter2_dna_2 --min-length 3000 --prep-for-dramv -i "/work2/microbiome/coral/Accelerate_project/analyses/viral_prep/metaspades_assemblies_dna/all_contigs_metaspades.fasta"

```

Instead I get the error: 
```
[2021-05-24 19:30 INFO] Step 2 - extract-feature finished.
[2021-05-24 19:30 ERROR] See error details in /work2/microbiome/coral/Accelerate_project/analyses/viral_prep/virsorter2_dna_2/log/iter-0/step3-classify/all-score-dsDNAphage.log
[Mon May 24 19:30:37 2021]
Error in rule classify_by_group:
    jobid: 64
    output: iter-0/dsDNAphage/all.pdg.clf
    conda-env: /work2/microbiome/db/virsorter/db/conda_envs/d7f02f59
    shell:

        Log=/work2/microbiome/coral/Accelerate_project/analyses/viral_prep/virsorter2_dna_2/log/iter-0/step3-classify/all-score-dsDNAphage.log
        python /work2/microbiome/conda/envs/virsorter/lib/python3.9/site-packages/virsorter/./scripts/classify.py iter-0/dsDNAphage/all.pdg.ftr /work2/microbiome/db/virsorter/db/group/dsDNAphage/model dsDNAphage iter-0/dsDNAphage/all.pdg.clf 2> $Log || { echo "See error details in $Log" | python /work2/microbiome/conda/envs/virsorter/lib/python3.9/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[2021-05-24 19:30 ERROR] See error details in /work2/microbiome/coral/Accelerate_project/analyses/viral_prep/virsorter2_dna_2/log/iter-0/step3-classify/all-score-ssDNA.log
[Mon May 24 19:30:37 2021]
Error in rule classify_by_group:
    jobid: 65
    output: iter-0/ssDNA/all.pdg.clf
    conda-env: /work2/microbiome/db/virsorter/db/conda_envs/d7f02f59
    shell:

        Log=/work2/microbiome/coral/Accelerate_project/analyses/viral_prep/virsorter2_dna_2/log/iter-0/step3-classify/all-score-ssDNA.log
        python /work2/microbiome/conda/envs/virsorter/lib/python3.9/site-packages/virsorter/./scripts/classify.py iter-0/ssDNA/all.pdg.ftr /work2/microbiome/db/virsorter/db/group/ssDNA/model ssDNA iter-0/ssDNA/all.pdg.clf 2> $Log || { echo "See error details in $Log" | python /work2/microbiome/conda/envs/virsorter/lib/python3.9/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message


*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues

```

I looked into the associated log files and got the following: 

```
/home/n10853430/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator MinMaxScaler from version 0.22.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/home/n10853430/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.22.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/home/n10853430/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.22.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/home/n10853430/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.22.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/home/n10853430/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator Pipeline from version 0.22.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
Traceback (most recent call last):
  File "/work2/microbiome/conda/envs/virsorter/lib/python3.9/site-packages/virsorter/./scripts/classify.py", line 77, in <module>
    main()
  File "/work2/microbiome/conda/envs/virsorter/lib/python3.9/site-packages/virsorter/./scripts/classify.py", line 68, in main
    pred_prob = model.predict_proba(X)
  File "/home/n10853430/.local/lib/python3.8/site-packages/sklearn/utils/metaestimators.py", line 120, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/home/n10853430/.local/lib/python3.8/site-packages/sklearn/pipeline.py", line 474, in predict_proba
    Xt = transform.transform(Xt)
  File "/home/n10853430/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 439, in transform
    if self.clip:
AttributeError: 'MinMaxScaler' object has no attribute 'clip'

```

**Comment by jiarong** [comment]
Hi, the error is caused by a package version mismatch. How did you installed VirSorter2?

**Comment by MeggyC** [comment]
Hi there, 
It was installed by our sys admin. Should I try re-installing in a different conda environment?

**Comment by jiarong** [comment]
Yes, that should solve this issue.

**Comment by sternp** [comment]
Hi Jiarong,

It was installed into a fresh environment. So the issue shouldn't be related to that.

**Comment by jiarong** [comment]
Hi, did you installed bioconda or development version? Did you add any modification to the tutorial in README?

**Comment by sternp** [comment]
bioconda, no modifications to the tutorial.

Will give the development version a crack.

**Comment by sternp** [comment]
Dev version worked. This issue can be closed I guess.

**Comment by jiarong** [comment]
I just looked at the error again and it shows the python package path is "/home/n10853430/.local/lib/python3.8/site-packages/sklearn/base.py", not the one in conda, so some kind of user level setup has changed the paths `conda activate`set up.

**Comment by liupfskygre** [comment]
Hi all，
      I reinstalled vs2 with exactly as the REASME, got the same error
```
conda create -n vs2 -c conda-forge -c bioconda virsorter=2
conda activate vs2
```

#try to restall and clear conda env, still there. 
```
/home/chenyy/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator MinMaxScaler from version 0.22.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/home/chenyy/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.22.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/home/chenyy/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.22.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/home/chenyy/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.22.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/home/chenyy/.local/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator Pipeline from version 0.22.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
Traceback (most recent call last):
  File "/home/chenyy/anaconda3/envs/vs222/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 77, in <module>
    main()
  File "/home/chenyy/anaconda3/envs/vs222/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 68, in main
    pred_prob = model.predict_proba(X)
  File "/home/chenyy/.local/lib/python3.8/site-packages/sklearn/utils/metaestimators.py", line 120, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/home/chenyy/.local/lib/python3.8/site-packages/sklearn/pipeline.py", line 474, in predict_proba
    Xt = transform.transform(Xt)
  File "/home/chenyy/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 439, in transform
    if self.clip:
AttributeError: 'MinMaxScaler' object has no attribute 'clip'

```

**Comment by jolespin** [comment]
Any way to override the snakemake conda environments?

**Comment by ReneKat** [comment]
Hello @jiarong _et. al._ 
I've loved using Virsorter2 and have had much success following the [protocol.io ](https://www.protocols.io/view/viral-sequence-identification-sop-with-virsorter2-bwm5pc86?step=4)

I'm seeing this issue with classify a few times in the issues, and I have tried all suggestings thus far to no avail. The weird part is that when I ran this VirSorter conda environment last on June 13, 2022, there were no issues using the same conda environment. 

Setup Details:
Linux Ubuntu 20.04
conda install

Error log:
`$ more /home/fch/Tools/virsorter-db/test.out/log/iter-0/step3-classify/all-score-ssDNA.log`

> /home/fch/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator MinMaxScaler from version 0.22.1 when using version
>  1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
> https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
>   warnings.warn(
> /home/fch/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.22.1 when usi
> ng version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
> https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
>   warnings.warn(
> /home/fch/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.22.1 when usi
> ng version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
> https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
>   warnings.warn(
> /home/fch/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator GridSearchCV from version 0.22.1 when using version
>  1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
> https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
>   warnings.warn(
> /home/fch/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator Pipeline from version 0.22.1 when using version 1.0
> .2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
> https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
>   warnings.warn(
> /home/fch/.local/lib/python3.8/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but MinMaxScaler was fitted without feature names
>   warnings.warn(
> Traceback (most recent call last):
>   File "/home/fch/miniconda3/envs/virus/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 77, in <module>
>     main()
>   File "/home/fch/miniconda3/envs/virus/lib/python3.8/site-packages/virsorter/./scripts/classify.py", line 68, in main
>     pred_prob = model.predict_proba(X)
>   File "/home/fch/.local/lib/python3.8/site-packages/sklearn/utils/metaestimators.py", line 113, in <lambda>
>     out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)  # noqa
>   File "/home/fch/.local/lib/python3.8/site-packages/sklearn/pipeline.py", line 535, in predict_proba
>     Xt = transform.transform(Xt)
>   File "/home/fch/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 506, in transform
>     if self.clip:
> AttributeError: 'MinMaxScaler' object has no attribute 'clip'

The issue that's been pointed out is that the $CONDA_PREFIX is not being used for sklearn
I have updated my PATH to that the $CONDA_PREFIX path is first
`$ echo $CONDA_PREFIX`

> /home/fch/miniconda3/envs/virus

`$ echo $PATH`

> /home/fch/miniconda3/envs/virus:/home/fch/.local/bin:/home/fch/bin:/home/fch/.local/bin:/home/fch/bin:/home/fch/miniconda3/envs/virus/bin:/home/fch/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin .....

added the $CONDA_PREFIX to the configuration profile

`$ echo CONDA_PREFIX: /home/fch/miniconda3/envs/virus >> /home/fch/miniconda3/envs/virus/lib/python3.8/site-packages/virsorter/template-config.yaml`

`$ tail /home/fch/miniconda3/envs/virus/lib/python3.8/site-packages/virsorter/template-config.yaml `

>   atg_perc, gtg_perc, ttg_perc, gc_mean, gc_sd, rbs_DoubleA, rbs_DoubleT, rbs_NoA,
>   rbs_None, rbs_OnlyA, rbs_OnlyT, rbs_Other, rbs_Other_GA, rbs_SD_Bacteroidetes, rbs_SD_Canonical,
>   rbs_TATATA_3-6, arc, bac, euk, vir, mix, unaligned, hallmark]
> attention: all model needs to be retrained if select feature changed
> SELECT_FEATURE_LIST: [gene_size, gene_overlap_perc, density, strand_switch_perc, atg_perc,
>   gtg_perc, ttg_perc, gc_mean, gc_sd, rbs_DoubleA, rbs_DoubleT, rbs_NoA, rbs_None,
>   rbs_OnlyA, rbs_OnlyT, rbs_Other, rbs_Other_GA, rbs_SD_Bacteroidetes, rbs_SD_Canonical,
>   rbs_TATATA_3-6, arc, bac, euk, vir, mix, unaligned, hallmark]
> DBDIR: /home/fch/Tools/virsorter-db/db
> CONDA_PREFIX: /home/fch/miniconda3/envs/virus

I tried installing the singularity version and was met by some odd screen (attached)
![Screen Shot 2022-09-05 at 12 06 00 PM (2)](https://user-images.githubusercontent.com/37948733/188500852-a9dc03ce-0beb-480e-86c5-173596001cd3.png)

Finally, I tried installing the development branch (option #2) and am having the exact same issue as with the conda install #1. 

Looking at the conda environment, the wanted scikit-learn is installed, but virsorter2 isn't using it. Even with an updated path.  
scikit-learn              0.22.1           py38hcdab131_1    conda-forge

I've attached my conda env:[vs2_conda_env.txt](https://github.com/jiarong/VirSorter2/files/9492584/vs2_conda_env.txt)

Thanks for any and all help! 
Take Care,
René

PS: I just updated my OS and conda, and still the same error. It also looks like Ubuntu 22 is available, so I'll try that next.

**Comment by jolespin** [comment]
Best of luck to you. I've switched to using VirFinder and, more recently, geNomad because the install worked like a charm every time and the output was straight forward. I've used VirSorter2 in the past and when it did work, it was great. Though, IIRC it took a lot longer to run than VirFinder. The main thing for me is the install and the output. I'm lazy these days.

**Comment by jiarong** [comment]
@ReneKat Looks like you have some setting causing `conda activate` not working.  One solution is to try append  `/home/fch/miniconda3/envs/virus/bin` instead to PATH. (you missed the last part `bin`...)

**Comment by ReneKat** [comment]
Hi @jiarong ,
thanks for your reply. Unfortunately, even with the bin added, I'm getting the same error. 
Instead, I went ahead and ignored that directory: 
`mv /home/fch/.local/lib/python3.8/site-packages/sklearn /home/fch/.local/lib/python3.8/site-packages/.sklearn`
I have no idea why this has become an issue, but this was my workaround. 
Hope it helps someone else. 
Best,
Rene
