### ISSUE TITLE
No rule to produce db

### ISSUE THREAD

**Issue by ponomarevsy** [jiarong/VirSorter2#7]
Hello,

We are having the following issue when Setting up VirSorter2 database:
```
(VirSorter2-2.0.beta) [user@node](:|✔)» virsorter setup --db-dir /path-to-virsorter-db db -j 4

[2020-09-30 09:52 INFO] Setting up VirSorter2 database; this might takes ~10 mins and only needs to be done once.
[2020-09-30 09:52 INFO] saving to /path-to-virsorter-db as DBDIR to config file /path-to-software/Anaconda3/2020.07/envs/VirSorter2-2.0.beta/lib/python3.8/site-packages/virsorter/template-config.yaml
MissingRuleException:
No rule to produce db (if you use input functions make sure that they don't raise unexpected exceptions).
[2020-09-30 09:52 ERROR] MissingRuleException:
No rule to produce db (if you use input functions make sure that they don't raise unexpected exceptions).
[2020-09-30 09:52 INFO] Setting up VirSorter2 database failed due to server not responding or bad internet connection; retrying..; please be patient.
MissingRuleException:
No rule to produce db (if you use input functions make sure that they don't raise unexpected exceptions).
```
There is nothing wrong with the Internet connection... is the VirSorter2 server up?

Please let us know. Thank you!

**Comment by jiarong** [comment]
Hi, thanks for the feedback. I can not reproduce this issue with either the latest bioconda version or development version. Could you try again on the development version and see if the problem still exists? Instructions are on the README page.

**Comment by ponomarevsy** [comment]
PS: We have this version of virsorter installed under Anaconda3/2020.07:
```
(VirSorter2-2.0.beta) [user@node](:|✔)» conda list virsorter
# packages in environment at /path/Anaconda3/2020.07/envs/VirSorter2-2.0.beta:
#
# Name                    Version                   Build  Channel
virsorter                 2.0.beta                   py_1    bioconda
```

**Comment by ponomarevsy** [comment]
This seems to work, though (but I don't like that it picked the default location for the db):

(VirSorter2-2.0.beta) [user@node](:|✔)» virsorter setup -d db -j 4
[2020-10-01 10:16 INFO] Setting up VirSorter2 database; this might takes ~10 mins and only needs to be done once.
[2020-10-01 10:16 INFO] saving to /path/Anaconda3/2020.07/envs/VirSorter2-2.0.beta/bin/db as DBDIR to config file /path/Anaconda3/2020.07/envs/VirSorter2-2.0.beta/lib/python3.8/site-packages/virsorter/template-config.yaml

Say, we'd like to move /path/Anaconda3/2020.07/envs/VirSorter2-2.0.beta/bin/db to a different location, how do we re-configure virsorter to point to the new location?

Please let us know. Thank you!

**Comment by jiarong** [comment]
You can use the location want during the install `virsorter setup -d /path/you/like/`
To change the database location after install, you can do the following:
```
# get the config file location
virsorter config --show-source
# then you can edit directly in that file to change DBDIR (at the bottom)
# or you can do this on command line:
virsorter config set DBDIR=/path/to/new/location/
```

**Comment by jiarong** [comment]
> PS: We have this version of virsorter installed under Anaconda3/2020.07:
> 
> ```
> (VirSorter2-2.0.beta) [user@node](:|✔)» conda list virsorter
> # packages in environment at /path/Anaconda3/2020.07/envs/VirSorter2-2.0.beta:
> #
> # Name                    Version                   Build  Channel
> virsorter                 2.0.beta                   py_1    bioconda
> ```

I actually tested this version yesterday and worked fine on end. What linux distribution are you using?

**Comment by ponomarevsy** [comment]
» hostnamectl
   Static hostname: ...
         Icon name: computer
        Machine ID: 285768d60c41406eb0e9beb903edd1fa
           Boot ID: 23a0168b663147f2bb13713fc9a81a71
  Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.2:GA:server
            Kernel: Linux 3.10.0-327.36.1.el7.x86_64
      Architecture: x86-64

**Comment by ponomarevsy** [comment]
This command did not work:

» virsorter config --show-source
Usage: virsorter [OPTIONS] COMMAND [ARGS]...
Try 'virsorter -h' for help.

Error: No such command 'config'.

» virsorter -h
Usage: virsorter [OPTIONS] COMMAND [ARGS]...

  virsorter - workflow for identifying viral sequences

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.

Commands:
  run            run virsorter main workflow
  setup          download reference files (~10GB) and install dependencies
  train-feature  subcommand for training feature of customized classifier
  train-model    subcommand for training customized classifier model

Can I 'vi' the 'template-config.yaml' file and set the DBDIR variable?

**Comment by jiarong** [comment]
It seems that you are not with the development version. Try `conda activate vs2` (vs2 could be whatever name you used when installing the development version).

Yes, you can just edit `template-config.yaml`.  But the development version is recommended.

**Comment by ponomarevsy** [comment]
I am using version 2.0.beta :

(VirSorter2-2.0.beta) [user@node](:|✔)» conda list virsorter
# packages in environment at /path/Anaconda3/2020.07/envs/VirSorter2-2.0.beta:
#
# Name                    Version                   Build  Channel
virsorter                 2.0.beta                   py_1    bioconda

Will edit the yaml file and export DBDIR varible. Hopefully, this will be enough. Thanks for your help!

**Comment by jiarong** [comment]
Editing the yaml file is enough. No need to export DBDIR in command line.

Right, your current version is installed by bioconda and should be fine to test the tool out.

More features has been added to development version and I have not get chance to upload to bioconda yet. It should look like this with `conda list virsorter`:
```
# packages in environment at /fs/project/PAS1117/jiarong/miniconda3/envs/vs2:
#
# Name                    Version                   Build  Channel
virsorter                 2.0a0                     dev_0    <develop>
```

**Comment by jiarong** [comment]
I just realized the `template-config.yaml` for your bioconda install is a little tricky to locate. It should be like this:
`/path/Anaconda3/2020.07/envs/VirSorter2-2.0.beta/lib/python3.8/site-packages/virsorter/template-config.yaml`. Editing in the one downloaded by `git clone` will NOT do anything.

**Comment by ponomarevsy** [comment]
Thanks for all your suggestions, @jiarong! You've been very helpful.
