### ISSUE TITLE
[Question] Has this been tested on detecting coronaviruses?

### ISSUE THREAD

**Issue by jolespin** [jiarong/VirSorter2#72]
I was wondering if this has been tested on extracting any type of coronaviruses (not just SARS-CoV-2) as this seems to be one of the newest viral detection algorithms out.

**Comment by jiarong** [comment]
We have tested on RNA viruses in soils.. The recommended score cutoff is >95%, and those contigs without hallmark gene needs manual check since this tool is only designed separate viral and nonviral, but not DNA virus and RNA virus..
