### ISSUE TITLE
error when run virsorter run

### ISSUE THREAD

**Issue by yuanpingdu** [jiarong/VirSorter2#74]
hi, when I run command "virsorter run" :
/usr/local/bin/virsorter run -i 120406A.contigs.fasta -w 120406A.virsorter2.out -j 4 all -d /virsorter2/db/ --use-conda-off true
it shows error :
MissingRuleException:
No rule to produce true (if you use input functions make sure that they don't raise unexpected exceptions).

when I not ues  paremater --use-conda-off it shows error :

CreateCondaEnvironmentException:
Could not create conda environment from /usr/local/lib/python3.6/dist-packages/virsorter-2.1-py3.6.egg/virsorter/rules/../envs/vs2.yaml:
usage: mamba [-h] [--version] [--slow SLOW] [--enable-coverage]
             [--coverage-file COVERAGE_FILE] [--format FORMAT] [--no-color]
             [--tags TAGS]
             [specs [specs ...]]
mamba: error: unrecognized arguments: --quiet --file /data/Project/metagenomics/jiangxinongda/meta_data_test/virus/virsorter2/db/conda_envs/60bfeee1.yaml --prefix /data/Project/metagenomics/jiangxinongda/meta_data_test/virus/virsorter2/db/conda_envs/60bfeee1

  File "/usr/local/lib/python3.6/dist-packages/snakemake/deployment/conda.py", line 352, in create

how should I to do make it run normally?

**Comment by jiarong** [comment]
Hi, `--use-conda-off` does not need `true` to follow it. I am not sure what the issue is here without `--use-conda-off`. Which version did you installed?

**Comment by yuanpingdu** [comment]
> Hi, `--use-conda-off` does not need `true` to follow it. I am not sure what the issue is here without `--use-conda-off`. Which version did you installed?

I have used  VirSorter 2.1

**Comment by jiarong** [comment]
How did you install it?

**Comment by yuanpingdu** [comment]
> How did you install it?

conda create -n vs2 -c conda-forge -c bioconda virsorter=2
conda activate vs2

**Comment by jiarong** [comment]
Did it work when you ran the test example after you install?

It looks like the version you are using now (/usr/local/bin/virsorter) does not look like to be installed by conda.

**Comment by yuanpingdu** [comment]
/usr/local/bin/miniconda3/envs/vs2/bin/virsorter  run -i /data/Project/metagenomics/jiangxinongda/meta_data_test/virus/virsorter2/120406A.contigs.fasta -w /data/Project/metagenomics/jiangxinongda/meta_data_test/virus/virsorter2/120406A.virsorter2.out -j 4 all -d /data/Project/metagenomics/jiangxinongda/meta_data_test/virus/virsorter2/db/ --use-conda-off
[2021-06-29 09:42 INFO] VirSorter 2.2.2

**Comment by yuanpingdu** [comment]
> Did it work when you ran the test example after you install?
> 
> It looks like the version you are using now (/usr/local/bin/virsorter) does not look like to be installed by conda.

It showed error too, when ran the test example.
I have installed the latest version V2.2.2, and it also showed error, the command is :
/usr/local/bin/miniconda3/envs/vs2/bin/virsorter  run -i /data/4seq.fa -w ./virsorter2.out -j 4 all -d /virsorter2/db/ --use-conda-off

errors:
[2021-06-30 01:20 INFO] # of seqs < 0 bp and removed: 0
[2021-06-30 01:20 INFO] # of circular seqs: 1
[2021-06-30 01:20 INFO] # of linear seqs  : 3
[2021-06-30 01:21 ERROR] See error details in iter-0/pp-linear.fna.splitdir/pp-linear.fna.18.split.pdg.log
[Wed Jun 30 01:21:00 2021]
Error in rule gene_call:
    jobid: 82
    output: iter-0/pp-linear.fna.splitdir/pp-linear.fna.18.split.pdg.splitgff, iter-0/pp-linear.fna.splitdir/pp-linear.fna.18.split.pdg.splitfaa
    shell:

        Log='iter-0/pp-linear.fna.splitdir/pp-linear.fna.18.split.pdg.log'
        prodigal -p meta -i iter-0/pp-linear.fna.splitdir/pp-linear.fna.18.split -a iter-0/pp-linear.fna.splitdir/pp-linear.fna.18.split.pdg.splitfaa -o iter-0/pp-linear.fna.splitdir/pp-linear.fna.18.split.pdg.splitgff -f gff  &> $Log || { echo "See error details in $Log" | python /usr/local/bin/miniconda3/envs/vs2/lib/python3.7/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        rm -f $Log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[2021-06-30 01:21 ERROR] See error details in iter-0/pp-linear.fna.splitdir/pp-linear.fna.15.split.pdg.log
[2021-06-30 01:21 ERROR] See error details in iter-0/pp-linear.fna.splitdir/pp-linear.fna.6.split.pdg.log
[Wed Jun 30 01:21:00 2021]
Error in rule gene_call:
    jobid: 88
    output: iter-0/pp-linear.fna.splitdir/pp-linear.fna.15.split.pdg.splitgff, iter-0/pp-linear.fna.splitdir/pp-linear.fna.15.split.pdg.splitfaa
    shell:

        Log='iter-0/pp-linear.fna.splitdir/pp-linear.fna.15.split.pdg.log'
        prodigal -p meta -i iter-0/pp-linear.fna.splitdir/pp-linear.fna.15.split -a iter-0/pp-linear.fna.splitdir/pp-linear.fna.15.split.pdg.splitfaa -o iter-0/pp-linear.fna.splitdir/pp-linear.fna.15.split.pdg.splitgff -f gff  &> $Log || { echo "See error details in $Log" | python /usr/local/bin/miniconda3/envs/vs2/lib/python3.7/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        rm -f $Log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[2021-06-30 01:21 ERROR] See error details in iter-0/pp-linear.fna.splitdir/pp-linear.fna.7.split.pdg.log
[Wed Jun 30 01:21:00 2021]
Error in rule gene_call:
    jobid: 74
    output: iter-0/pp-linear.fna.splitdir/pp-linear.fna.6.split.pdg.splitgff, iter-0/pp-linear.fna.splitdir/pp-linear.fna.6.split.pdg.splitfaa
    shell:

        Log='iter-0/pp-linear.fna.splitdir/pp-linear.fna.6.split.pdg.log'
        prodigal -p meta -i iter-0/pp-linear.fna.splitdir/pp-linear.fna.6.split -a iter-0/pp-linear.fna.splitdir/pp-linear.fna.6.split.pdg.splitfaa -o iter-0/pp-linear.fna.splitdir/pp-linear.fna.6.split.pdg.splitgff -f gff  &> $Log || { echo "See error details in $Log" | python /usr/local/bin/miniconda3/envs/vs2/lib/python3.7/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        rm -f $Log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Wed Jun 30 01:21:00 2021]
Error in rule gene_call:
    jobid: 85
    output: iter-0/pp-linear.fna.splitdir/pp-linear.fna.7.split.pdg.splitgff, iter-0/pp-linear.fna.splitdir/pp-linear.fna.7.split.pdg.splitfaa
    shell:

        Log='iter-0/pp-linear.fna.splitdir/pp-linear.fna.7.split.pdg.log'
        prodigal -p meta -i iter-0/pp-linear.fna.splitdir/pp-linear.fna.7.split -a iter-0/pp-linear.fna.splitdir/pp-linear.fna.7.split.pdg.splitfaa -o iter-0/pp-linear.fna.splitdir/pp-linear.fna.7.split.pdg.splitgff -f gff  &> $Log || { echo "See error details in $Log" | python /usr/local/bin/miniconda3/envs/vs2/lib/python3.7/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        rm -f $Log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message


*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
