### ISSUE TITLE
Snakemake missing output files reason while using Slurm

### ISSUE THREAD

**Issue by paulaistvan** [jiarong/VirSorter2#75]
Command:

<img width="1436" alt="Screenshot 2021-07-04 at 11 54 13" src="https://user-images.githubusercontent.com/85185437/124380739-9d8b9680-dcbe-11eb-8f51-77b690d25182.png">

Error

<img width="781" alt="Screenshot 2021-07-04 at 11 53 13" src="https://user-images.githubusercontent.com/85185437/124380705-6b7a3480-dcbe-11eb-9aa1-fcef04f6160b.png">

While running normally without submitting job, snakemake is working fine but if i use slurm to submit job via sbatch, then it give missing output files in reason and then job fails.

Tried putting latency wait variable for snakemake also as per internet results that suggested will wait for output files to generate but no luck, any insights on this? 

Have tried reducing mem per cpu, no of nodes, cpus etc but no luck.

This is the snakemake rule, pls note it work perfect if we don't submit job via slurm.

<img width="1230" alt="Screenshot 2021-07-04 at 11 57 38" src="https://user-images.githubusercontent.com/85185437/124380788-0a9f2c00-dcbf-11eb-9596-fda1c59e5138.png">

**Comment by jiarong** [comment]
Hi, this is more of a snakemake Q. The issues I can spot are:
- In `params`, `dir=virsorter2_output2/{sample}` ==> `dir=f"virsorter2_output2/{wildcards.sample}"`
- In `output`, remove `touch`

**Comment by paulaistvan** [comment]
Thank you for you quick answer. I added both of your suggestions, but got some other error.

_name 'wildcards' is not defined._

and if i simply do the old one in params section but with f added, like this:
dir=f"virsorter_output2/{sample}"

then it says,
_name 'sample' is not defined._

Can you suggest what could be the reason.

**Comment by jiarong** [comment]
I recommend removing the `params`, change the shell command to:
```
virsorter run -i {input.fasta} -d {config[db]} -w virsorter_output2/{wildcards.sample} -j {threads} --min-length 1500 --use-conda-off all
```

**Comment by paulaistvan** [comment]
Have changed as per your suggestions, below is final one. It's still giving same error.

<img width="1400" alt="Screenshot 2021-07-06 at 17 27 16" src="https://user-images.githubusercontent.com/85185437/124627033-7fb95f80-de7f-11eb-967e-a6bd6b5a31e4.png">

Error:
<img width="809" alt="Screenshot 2021-07-06 at 17 27 22" src="https://user-images.githubusercontent.com/85185437/124626971-6f08e980-de7f-11eb-8520-29b49f64395f.png">

**Comment by jiarong** [comment]
Are there files produced in `virsorter_output2/sample/`?

**Comment by paulaistvan** [comment]
Yes, only this:

<img width="219" alt="Screenshot 2021-07-07 at 08 01 17" src="https://user-images.githubusercontent.com/85185437/124707937-d1063500-def9-11eb-9814-0dd3ff8580e0.png">

**Comment by paulaistvan** [comment]
But the folder name is "sample" should be the name of the scaffold right?

**Comment by jiarong** [comment]
Name should be whatever is under "SampleData2". Any message produced from VS2?

**Comment by paulaistvan** [comment]
yes name is fine, and by message you mean log folder or on the terminal output that you have already seen above?
In the log folder, there is only one empty file.

<img width="107" alt="Screenshot 2021-07-08 at 19 03 48" src="https://user-images.githubusercontent.com/85185437/124962689-3b64c580-e01f-11eb-9462-9bc717c54404.png">

**Comment by jiarong** [comment]
Hi, sorry that I have not clue what's the issue. The snakemake syntax looks good to me and the VS2 runs OK without snakemake. . It will require the data and some testing to figure out. But I wont be able to solve this snakemake slurm issue for you here.

**Comment by erosix** [comment]
I have the same issue. Was a solution found?
 I see that this happens when the rule outputs are not specified in the shell commands directly. Like if the output is a produced file but in the shell command one only specifies the output folder and not the internal files.

**Comment by jgroh** [comment]
Experiencing a similar issue here.

**Comment by ETAOIK** [comment]
Experiencing a similar issue here.
