### ISSUE TITLE
Possible to leverage this tool for classifying short reads?

### ISSUE THREAD

**Issue by UCRajkumar** [jiarong/VirSorter2#85]
I realize this tool is used to classify viral genomes. However, is it possible to leverage this tool to classify short reads (150 bp) as viral/non-viral?

**Comment by jiarong** [comment]
Hi, VirSorter2 is not suitable for short reads. Kmer-based methods such as DeepVirFinder have better performance on shorter sequences (<3kb), but still does NOT work well with short reads..
