### ISSUE TITLE
Lack of environment:vs2

### ISSUE THREAD

**Issue by gubingyu** [jiarong/VirSorter2#92]
安装conda activate vs2时候，出现error： Could not find conda environment: vs2 You can list all discoverable environments with `conda info --envs`pen ，list后确实没有这个环境，请问是为什么，后续就没接着安装了，就是照着第一个步骤安装的。请问怎么解决？感谢

**Comment by jiarong** [comment]
Hi, that means the first step `conda create -n vs2 -c conda-forge -c bioconda virsorter=2` did not complete. Also make sure you are doing this on Linux OS.

**Comment by gubingyu** [comment]
Thanks a lot,I will reinstall step 1
