### ISSUE TITLE
Error in rule hmmsearch

### ISSUE THREAD

**Issue by cmf1997** [jiarong/VirSorter2#94]
hi! 
the virsorteri used were installed by Conda, the version is 2.2.3
when I try the test.fa by 'virsorter run -w test.out -i test.fa --min-length 5000 -j 4 all'
after Step 1 - preprocess finished. the error occurred

Error in rule hmmsearch:
    jobid: 103
    output: iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl
    conda-env: /lustre/home/acct-medzy/medzy-cai/.conda/envs/viral/bin/db-vs2/conda_envs/6e68d5c2
    shell:
        
        Domain=Viruses
        if [ $Domain = "Viruses" ]; then
            Hmmdb=/lustre/home/acct-medzy/medzy-cai/.conda/envs/viral/bin/db-vs2/hmm/viral/combined.hmm
        else
            Domain2=$Domain
            if [ $Domain2 = "Pfamviruses" ]; then
                Domain2=Viruses
            fi
            Hmmdb=/lustre/home/acct-medzy/medzy-cai/.conda/envs/viral/bin/db-vs2/hmm/pfam/Pfam-A-"$Domain2".hmm
        fi

        Bname=$(basename iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split)
        To_scratch=false
        # move the heavy IO of hmmsearch in local scratch if possible
        if [ -d "/tmp" ]; then
            # not sure df or du are compatible in all linux; use "||To_scratch=false" 
            #   to prevent imcompatibility in some linux distro
            Tmp=$(mktemp -d /tmp/vs2-XXXXXXXXXXXX) && To_scratch=true || To_scratch=false
            Avail=$(df -P /tmp | awk 'END{print $4}') || To_scratch=false
            Fsize=$(du -k iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split | awk '{print $1*5}') || To_scratch=false
            if [ "$Avail" -gt "$Fsize" ] && [ "$To_scratch" = "true" ]; then
                cp iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split $Tmp/$Bname || To_scratch=false
            else
                To_scratch=false
            fi
        fi

        hmmsearch -h | grep '^# HMMER' > iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl.log
        if [ "$To_scratch" = false ]; then
            # local scratch not set or not enough space in local scratch
            hmmsearch -T 30 --tblout iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl --cpu 4 --noali $Hmmdb iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split > /dev/null 2>> iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl.log || { echo "See error details in /lustre/home/acct-medzy/medzy-cai/data/test-liver/LC2-1/spades_out4/vsresult/test.out/iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl.log" | python /lustre/home/acct-medzy/medzy-cai/.conda/envs/viral/lib/python3.6/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        else
            # when To_scratch is true, Tmp and Bname should have been defined successfully
            hmmsearch -T 30 --tblout iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl --cpu 4 --noali $Hmmdb $Tmp/$Bname > /dev/null 2>> iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl.log || { echo "See error details in /lustre/home/acct-medzy/medzy-cai/data/test-liver/LC2-1/spades_out4/vsresult/test.out/iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl.log" | python /lustre/home/acct-medzy/medzy-cai/.conda/envs/viral/lib/python3.6/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }

            rm -f $Tmp/$Bname && rmdir $Tmp
        fi
        rm -f iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

Thanks for your help.

**Comment by cmf1997** [comment]
@jiarong any suggestions would be much appreciated

**Comment by jiarong** [comment]
Hi, which OS are you running this on? Are there any other error message saying "core dump" or "segfault"?

**Comment by cmf1997** [comment]
thanks for your response,
the &nbsp;OS is&nbsp;CentOS Linux release 7.7.1908 (Core)
I didn't notice core dump or segfault
I rerun the command
the complete command and output are shown in the attached file








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiarong/VirSorter2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 凌晨1:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiarong/VirSorter2] Error in rule hmmsearch (Issue #94)





 
Hi, which OS are you running this on? Are there any other error message saying "core dump" or "segfault"?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiarong** [comment]
It looks like the output from your rerun is not attached?

**Comment by cmf1997** [comment]
[error.txt](https://github.com/jiarong/VirSorter2/files/7689561/error.txt)
[erroe2.txt](https://github.com/jiarong/VirSorter2/files/7689562/erroe2.txt)

**Comment by cmf1997** [comment]
Sorry about that
there were two error when I rerun the command

**Comment by jiarong** [comment]
Hi, both log files show memory error from hmmsearch (probably ran out of memory). Make sure there are sufficient memory. You can also reduce `-j` to reduce memory required (but also reduce speed).
In case of such errors, you can run the same exact command line. VS2 can find where it failed previously and continue from there..

**Comment by cmf1997** [comment]
Really thanks for your reply.
I think that would solve my question.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiarong/VirSorter2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月14日(星期二) 上午6:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiarong/VirSorter2] Error in rule hmmsearch (Issue #94)





 
Hi, both log files show memory error from hmmsearch (probably ran out of memory). Make sure there are sufficient memory. You can also reduce -j to reduce memory required (but also reduce speed).
 In case of such errors, you can run the same exact command line. VS2 can find where it failed previously and continue from there..
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cmf1997** [comment]
hi jiarong 
the problem still bothers me, i used less cpu core but it did not work sometimes
is there anything i can do to limit the memory usage? 
any idea would be appreciated~

**Comment by jiarong** [comment]
The conda installation might have issue with certain OS with specific setting. Check out the [singularity version](https://github.com/jiarong/VirSorter2#option-3), and see if it solves the issue.

**Comment by cmf1997** [comment]
thanks a lot!!!!!!
I tried the singularity version with same error, but sometimes it works, so may there is something wrong with the hpc setting!
