### ISSUE TITLE
Error with circular-linear-split.py

### ISSUE THREAD

**Issue by Adarsh931** [jiarong/VirSorter2#96]
virsorter run -w test_results/test_results.out -i 8seq.fa -j 16 --rm-tmpdir
[2021-12-14 11:51 INFO] VirSorter 2.2.3
[2021-12-14 11:51 INFO] /workdir/as2783/miniconda3/envs/vs2/bin/virsorter run -w test_results/test_results.out -i 8seq.fa -j 16 --rm-tmpdir
[2021-12-14 11:51 INFO] Using /local/workdir/as2783/VirSorter2/virsorter/template-config.yaml as config template
[2021-12-14 11:51 INFO] conig file written to /local/workdir/as2783/VirSorter2/test/test_results/test_results.out/config.yaml

[2021-12-14 11:51 INFO] Executing: snakemake --snakefile /local/workdir/as2783/VirSorter2/virsorter/Snakefile --directory /local/workdir/as2783/VirSorter2/test/test_results/test_results.out --jobs 16 --configfile /local/workdir/as2783/VirSorter2/test/test_results/test_results.out/config.yaml --latency-wait 600 --rerun-incomplete --nolock  --conda-frontend mamba --conda-prefix /local/workdir/refdbs/virsorter2_db/db/conda_envs --use-conda    --quiet  all
Job counts:
        count   jobs
        1       all
        1       check_point_for_reclassify
        1       circular_linear_split
        1       classify
        2       classify_by_group
        2       classify_full_and_part_by_group
        1       combine_linear_circular
        2       combine_linear_circular_by_group
        1       extract_feature
        1       extract_provirus_seqs
        1       finalize
        1       gff_feature
        2       gff_feature_by_group
        2       hmm_features_by_group
        1       hmm_sort_to_best_hit_taxon
        2       hmm_sort_to_best_hit_taxon_by_group
        1       merge_classification
        1       merge_full_and_part_classification
        2       merge_hmm_gff_features_by_group
        2       merge_provirus_call_by_group_by_split
        1       merge_provirus_call_from_groups
        5       merge_split_hmmtbl
        10      merge_split_hmmtbl_by_group
        10      merge_split_hmmtbl_by_group_tmp
        1       pick_viral_fullseq
        1       preprocess
        1       split_faa
        2       split_faa_by_group
        2       split_gff_by_group
        61
  File "/local/workdir/as2783/VirSorter2/virsorter/./scripts/circular-linear-split.py", line 63
    mes = (f'Duplicate seqname detected in {infile}; '
                                                     ^
SyntaxError: invalid syntax
[Tue Dec 14 11:51:21 2021]
Error in rule circular_linear_split:
    jobid: 8
    output: iter-0/pp-seqname-length.tsv
    conda-env: /local/workdir/refdbs/virsorter2_db/db/conda_envs/27fb3f39
    shell:

        # prep_logdir
        mkdir -p log/iter-0/step1-pp log/iter-0/step2-extract-feature log/iter-0/step3-classify

        Cnt=$(grep -c '^>' /local/workdir/as2783/VirSorter2/test/8seq.fa)
        if [ ${Cnt} = 0 ]; then
            echo "No sequnences found in contig file; exiting"               | python /local/workdir/as2783/VirSorter2/virsorter/./scripts/echo.py --level error
            exit 1
        fi

        python /local/workdir/as2783/VirSorter2/virsorter/./scripts/circular-linear-split.py           /local/workdir/as2783/VirSorter2/test/8seq.fa           iter-0/pp-circular.fna.preext          iter-0/pp-linear.fna           iter-0/pp-seqname-length.tsv           "||rbs:common"           0

        if [ ! -s iter-0/pp-circular.fna.preext ]; then
            echo "No circular seqs found in contig file"               | python /local/workdir/as2783/VirSorter2/virsorter/./scripts/echo.py
            rm iter-0/pp-circular.fna.preext
        else
            python /local/workdir/as2783/VirSorter2/virsorter/./scripts/circular-extend.py               iter-0/pp-circular.fna.preext iter-0/pp-circular.fna
        fi

        if [ ! -s iter-0/pp-linear.fna ]; then
            echo "No linear seqs found in contig file"               | python /local/workdir/as2783/VirSorter2/virsorter/./scripts/echo.py
            rm iter-0/pp-linear.fna
        fi

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues

Also, I checked python --version: 3.8.12; and pip --version: 21.3.1

**Comment by Adarsh931** [comment]
Please close this, it's already solved. Thank you!

**Comment by JiaLonghao1997** [comment]
I got the same errors. How to solve this problem? Could you give me some advice? Thank you.
```
[Mon Aug 15 16:36:12 2022]
Error in rule circular_linear_split:
    jobid: 11
    output: iter-0/pp-seqname-length.tsv
    conda-env: /share/inspurStorage/home1/jialh/human_virome/tools/db/conda_envs/c5c11330
    shell:
        
        # prep_logdir
        mkdir -p log/iter-0/step1-pp log/iter-0/step2-extract-feature log/iter-0/step3-classify

        Cnt=$(grep -c '^>' /share/inspurStorage/home3/ZXMGroup/VIROME/G3compare/results/04UHGG/test.fa)
        if [ ${Cnt} = 0 ]; then
            echo "No sequnences found in contig file; exiting"               | python /home1/jialh/tools/miniconda3/envs/vs2/lib/python3.6/site-packages/virsorter/./scripts/echo.py --level error
            exit 1
        fi 

        python /home1/jialh/tools/miniconda3/envs/vs2/lib/python3.6/site-packages/virsorter/./scripts/circular-linear-split.py           /share/inspurStorage/home3/ZXMGroup/VIROME/G3compare/results/04UHGG/test.fa           iter-0/pp-circular.fna.preext          iter-0/pp-linear.fna           iter-0/pp-seqname-length.tsv           "||rbs:common"           1500

        if [ ! -s iter-0/pp-circular.fna.preext ]; then
            echo "No circular seqs found in contig file"               | python /home1/jialh/tools/miniconda3/envs/vs2/lib/python3.6/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-circular.fna.preext
        else
            python /home1/jialh/tools/miniconda3/envs/vs2/lib/python3.6/site-packages/virsorter/./scripts/circular-extend.py               iter-0/pp-circular.fna.preext iter-0/pp-circular.fna
        fi

        if [ ! -s iter-0/pp-linear.fna ]; then
            echo "No linear seqs found in contig file"               | python /home1/jialh/tools/miniconda3/envs/vs2/lib/python3.6/site-packages/virsorter/./scripts/echo.py
            rm iter-0/pp-linear.fna
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```
Exiting because a job execution failed. Look above for error message


*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues
