### ISSUE TITLE
confict between final-viral-boundary file and the actual viral sequence

### ISSUE THREAD

**Issue by mujiezhang** [jiarong/VirSorter2#99]
I find sometimes the boundary in final-viral-boundary file is not consistent with the actual location of viral fna in host sequence.

for example:
seqname | trim_orf_index_start | trim_orf_index_end | trim_bp_start | trim_bp_end | trim_pr | trim_pr_max | prox_orf_index_start | prox_orf_index_end | prox_bp_start | prox_bp_end | prox_pr | prox_pr_max | partial | full_orf_index_start | full_orf_index_end | full_bp_start | full_bp_end | pr_full | arc | bac | euk | vir | mix | unaligned | hallmark_cnt | group | shape |
NZ_QODQ01000032.1 | 1 | 70 | 309 | 50289 | 1 | 1 | 1 | 70 | 309 | 50289 | nan | nan | 0 | 1 | 70 | 309 | 50289 | 1 | 0 | 11.4 | 0 | 64.3 | 4.3 | 20 | 22 | dsDNAphage | linear 

but the actual viral fna the virsorter2 gives starts at the first bp in host sequence.
So is there any explanation for this ?

**Comment by jiarong** [comment]
Did you use the `--keep-original-seq` option? This option keeps  the original sequence unless it's the prophage.

**Comment by mujiezhang** [comment]
yes, I use the --keep-original-seq option. Maybe I find the reason. If the virus is labeled full, then the viral fna is the full contig of host. And if the virus is labeled prophage, then the viral boundary is exactly the boundary in the boundary file. Does it right?

**Comment by jiarong** [comment]
Correct. If you remove "--keep-original-seq", both "full" and "partial" will match the boundary.

**Comment by mujiezhang** [comment]
Thank you very much !
